import { describe, it, expect } from "vitest";
import { readFileSync, existsSync } from "fs";

describe("model-meta.json (written by embed-chunks-remote.mjs)", () => {
  it("exists with the fields search.js needs at runtime", () => {
    const path = "public/models/bge-base-en-v1.5-q4/model-meta.json";
    if (!existsSync(path)) {
      // Generated by `npm run search:embed`. Allow absence in clean clones;
      // search.js falls back to text-only when meta is missing.
      return;
    }
    const meta = JSON.parse(readFileSync(path, "utf-8"));
    expect(meta.dim).toBe(768);
    expect(typeof meta.checksum).toBe("string");
    expect(meta.queryInstruction).toMatch(/^Represent /);
  });
});
