export const chapters = [
  { id: "0", title: "Table of Contents", section: 0, component: "TOC", file: "table-of-contents/toc" },
  // Section 1: Neural Network Foundations
  { id: "1.1", title: "What is a Neural Network?", section: 1, component: "WhatIsNN", file: "neural-foundations/what-is-nn" },
  { id: "1.2", title: "Inside a Single Neuron", section: 1, component: "InsideNeuron", file: "neural-foundations/inside-neuron" },
  { id: "1.3", title: "What is a Layer?", section: 1, component: "WhatIsLayer", file: "neural-foundations/what-is-layer" },
  { id: "1.4", title: "Weights & Biases - The Knobs", section: 1, component: "WeightsBiases", file: "neural-foundations/weights-biases" },
  { id: "1.5", title: "Why Linear Isn't Enough", section: 1, component: "WhyLinear", file: "neural-foundations/why-linear" },
  { id: "1.6", title: "Activation (ReLU) - Why Layers Need a Bend", section: 1, component: "ReLU", file: "neural-foundations/re-lu" },
  { id: "1.7", title: "The Forward Pass - Full Example", section: 1, component: "ForwardPass", file: "neural-foundations/forward-pass" },
  { id: "1.8", title: "Loss - How Wrong Were We?", section: 1, component: "LossFunction", file: "neural-foundations/loss-function" },
  { id: "1.9", title: "Learning - What Does It Mean?", section: 1, component: "WhatIsLearning", file: "neural-foundations/what-is-learning" },
  { id: "1.10", title: "Derivatives - The Core Intuition", section: 1, component: "Derivatives", file: "neural-foundations/derivatives" },
  { id: "1.11", title: "The Backward Pass - The Chain Rule", section: 1, component: "BackwardPass", file: "neural-foundations/backward-pass" },
  { id: "1.12", title: "Gradient Descent - Fixing the Weights", section: 1, component: "GradientDescent", file: "neural-foundations/gradient-descent" },
  { id: "1.13", title: "Backprop Through the Real Network", section: 1, component: "BackpropRealNetwork", file: "neural-foundations/backprop-real-network" },
  { id: "1.14", title: "Gradients in Action - The Full Training Loop", section: 1, component: "GradientsInAction", file: "neural-foundations/gradients-in-action" },
  { id: "1.15", title: "Why Deep Backprop Gets Hard", section: 1, component: "WhyBackpropHard", file: "neural-foundations/why-backprop-hard" },
  { id: "1.16", title: "Vectors - Numbers That Travel Together", section: 1, component: "Vectors", file: "neural-foundations/vectors" },
  { id: "1.17", title: "The Dot Product - How Vectors Compare", section: 1, component: "DotProductIntro", file: "neural-foundations/dot-product-intro" },
  { id: "1.18", title: "Matrices - Grids That Transform Vectors", section: 1, component: "Matrices", file: "neural-foundations/matrices" },
  { id: "1.19", title: "A Layer is Matrix Multiplication", section: 1, component: "LayerIsMatMul", file: "neural-foundations/layer-is-mat-mul" },
  { id: "1.20", title: "Activation Functions - The Full Picture", section: 1, component: "ActivationFunctions", file: "neural-foundations/activation-functions" },
  { id: "1.21", title: 'What "Deep" Really Means', section: 1, component: "WhatDeepMeans", file: "neural-foundations/what-deep-means" },
  { id: "1.22", title: "Same Building Blocks, Different Shapes", section: 1, component: "SameBuildingBlocks", file: "neural-foundations/same-building-blocks" },
  { id: "1.23", title: "Dropout - The Regularization Trick", section: 1, component: "Dropout", file: "neural-foundations/dropout" },
  { id: "1.24", title: "Adam - The Real Optimizer", section: 1, component: "AdamOptimizer", file: "neural-foundations/adam-optimizer" },
  { id: "1.25", title: "Learning Rate Warmup & Decay", section: 1, component: "LRWarmupDecay", file: "neural-foundations/lr-warmup-decay" },
  { id: "1.26", title: "Weight Initialization - How Random?", section: 1, component: "WeightInit", file: "neural-foundations/weight-init" },
  // Section 2: How LLMs Actually Train (reordered: output/generation before fine-tuning)
  { id: "2.1", title: "Tokenization - From Words to Numbers", section: 2, component: "Tokenization", file: "llm-training/tokenization" },
  { id: "2.2", title: "Self-Supervised Learning - How GPT Trains", section: 2, component: "SelfSupervised", file: "llm-training/self-supervised" },
  { id: "2.3", title: "Cross-Entropy Loss - The LLM Score", section: 2, component: "CrossEntropy", file: "llm-training/cross-entropy" },
  { id: "2.4", title: "The Neural Network in Action", section: 2, component: "NNInAction", file: "llm-training/nn-in-action" },
  { id: "2.5", title: "The Output Layer - From Hidden State to Words", section: 2, component: "OutputLayer", file: "llm-training/output-layer" },
  {
    id: "2.6",
    title: "Autoregressive Generation - One Token at a Time",
    section: 2,
    component: "AutoregressiveGeneration",
    file: "llm-training/autoregressive-generation",
  },
  { id: "2.7", title: "Supervised Fine-Tuning (SFT)", section: 2, component: "SFT", file: "llm-training/sft" },
  { id: "2.8", title: "RLHF - Making AI Helpful & Safe", section: 2, component: "RLHF", file: "llm-training/rlhf" },
  { id: "2.9", title: "DPO - Simpler Alignment", section: 2, component: "DPO", file: "llm-training/dpo" },
  {
    id: "2.10",
    title: "Tokenizer Deep Dive - BPE, WordPiece, SentencePiece",
    section: 2,
    component: "TokenizerDeepDive",
    file: "llm-training/tokenizer-deep-dive",
  },
  // Section 3: Scaling & Modern Techniques (BatchTraining added)
  { id: "3.1", title: "Scaling Laws - Why Bigger Models Win", section: 3, component: "ScalingLaws", file: "scaling/scaling-laws" },
  { id: "3.2", title: "Parameters at Scale", section: 3, component: "ParametersAtScale", file: "scaling/parameters-at-scale" },
  { id: "3.3", title: "Batch Training - Why Not One Example at a Time?", section: 3, component: "BatchTraining", file: "llm-training/batch-training" },
  { id: "3.4", title: "Knowledge Distillation - Teacher to Student", section: 3, component: "Distillation", file: "scaling/distillation" },
  { id: "3.5", title: "CLIP - Teaching AI to See & Read", section: 3, component: "CLIP", file: "scaling/clip" },
  { id: "3.6", title: "The Complete Training Pipeline", section: 3, component: "TrainingPipeline", file: "scaling/training-pipeline" },
  // Section 4: The Road to Transformers (trimmed: encoder/decoder moved to Sections 8-9)
  { id: "4.1", title: "CNN", section: 4, component: "CNN", file: "road-to-transformers/cnn" },
  { id: "4.2", title: "RNN", section: 4, component: "RNN", file: "road-to-transformers/rnn" },
  { id: "4.3", title: "RNN's Fatal Flaws", section: 4, component: "RNNFlaws", file: "road-to-transformers/rnn-flaws" },
  { id: "4.4", title: "The Transformer Arrives", section: 4, component: "TransformerArrives", file: "road-to-transformers/transformer-arrives" },
  // Section 5: Transformer Input Pipeline (trimmed: WhatTransformerDoes moved to Section 9)
  { id: "5.1", title: "The Full Architecture", section: 5, component: "FullArchitecture", file: "transformer-input/full-architecture" },
  { id: "5.2", title: "Zoom: Embeddings", section: 5, component: "Embeddings", file: "transformer-input/embeddings" },
  { id: "5.3", title: "Positional Encoding - The Problem", section: 5, component: "PosEncodingProblem", file: "transformer-input/pos-encoding-problem" },
  { id: "5.4", title: "Positional Encoding - The Formula", section: 5, component: "PosEncodingFormula", file: "transformer-input/pos-encoding-formula" },
  { id: "5.5", title: "Positional Encoding - Computing Positions", section: 5, component: "PosEncodingCompute", file: "transformer-input/pos-encoding-compute" },
  { id: "5.6", title: "Positional Encoding - Fast vs Slow", section: 5, component: "PosEncodingFastSlow", file: "transformer-input/pos-encoding-fast-slow" },
  { id: "5.7", title: "Positional Encoding - Final Addition", section: 5, component: "PosEncodingFinal", file: "transformer-input/pos-encoding-final" },
  { id: "5.8", title: "Positional Encoding - The Heatmap", section: 5, component: "PosEncodingHeatmap", file: "transformer-input/pos-encoding-heatmap" },
  { id: "5.9", title: "RoPE - Rotary Position Embeddings", section: 5, component: "RoPE", file: "transformer-input/ro-pe" },
  // Section 6: Attention - Understanding Q, K, V
  { id: "6.1", title: "The Problem - Context is Everything", section: 6, component: "ContextProblem", file: "attention-qkv/context-problem" },
  { id: "6.2", title: "How Does a Word Look At Others?", section: 6, component: "WordLookup", file: "attention-qkv/word-lookup" },
  { id: "6.3", title: "The Dot Product - Measuring Similarity", section: 6, component: "DotProduct", file: "attention-qkv/dot-product" },
  { id: "6.4", title: "Why Not Dot Product Embeddings Directly?", section: 6, component: "WhyNotDirectDot", file: "attention-qkv/why-not-direct-dot" },
  { id: "6.5", title: "Q, K, V - The Classroom Analogy", section: 6, component: "QKVClassroom", file: "attention-qkv/qkv-classroom" },
  { id: "6.6", title: "Every Word is Both Asker and Answerer", section: 6, component: "AskerAnswerer", file: "attention-qkv/asker-answerer" },
  { id: "6.7", title: "Why Can\'t Key and Value Be the Same?", section: 6, component: "WhyKVDifferent", file: "attention-qkv/why-kv-different" },
  { id: "6.8", title: "The Google Search Analogy", section: 6, component: "GoogleAnalogy", file: "attention-qkv/google-analogy" },
  { id: "6.9", title: "How Are Q, K, V Created?", section: 6, component: "HowQKVCreated", file: "attention-qkv/how-qkv-created" },
  { id: "6.10", title: "Shapes - Why Q is Smaller Than the Embedding", section: 6, component: "QKVShapes", file: "attention-qkv/qkv-shapes" },
  { id: "6.11", title: "W Matrices - Learned During Training", section: 6, component: "WMatrices", file: "attention-qkv/w-matrices" },
  { id: "6.12", title: "Tracing a Complete Example", section: 6, component: "TracingExample", file: "attention-qkv/tracing-example" },
  // Section 7: Attention - The Full Computation (CausalMask/CrossAttention moved to Section 9)
  { id: "7.1", title: "Step 1 - Compute Q, K, V for Every Word", section: 7, component: "ComputeQKV", file: "attention-computation/compute-qkv" },
  { id: "7.2", title: "Step 2 - Attention Scores (Dot Products)", section: 7, component: "AttentionScores", file: "attention-computation/attention-scores" },
  { id: "7.3", title: "Why K Transpose? - Making the Shapes Fit", section: 7, component: "KTranspose", file: "attention-computation/k-transpose" },
  { id: "7.4", title: "Why Do We Need Softmax?", section: 7, component: "WhySoftmax", file: "attention-computation/why-softmax" },
  { id: "7.5", title: "Step 3 - Scale by \u221Ad_k", section: 7, component: "ScaleByRootDk", file: "attention-computation/scale-by-root-dk" },
  { id: "7.6", title: "Step 4 - Softmax \u2192 Probabilities", section: 7, component: "SoftmaxProbs", file: "attention-computation/softmax-probs" },
  { id: "7.7", title: "Step 5 - Weighted Sum of Values", section: 7, component: "WeightedSum", file: "attention-computation/weighted-sum" },
  { id: "7.8", title: "The Full Formula", section: 7, component: "FullFormula", file: "attention-computation/full-formula" },
  { id: "7.9", title: "Why Multi-Head? - The Compromise Problem", section: 7, component: "WhyMultiHead", file: "attention-computation/why-multi-head" },
  { id: "7.10", title: "The Split - How 8 Heads Work", section: 7, component: "HeadSplit", file: "attention-computation/head-split" },
  { id: "7.11", title: "Inside Each Head - Full Attention in 64 Dims", section: 7, component: "InsideEachHead", file: "attention-computation/inside-each-head" },
  { id: "7.12", title: "Concat + W_O - Blending All Heads", section: 7, component: "ConcatWO", file: "attention-computation/concat-w-o" },
  { id: "7.13", title: "Why 8 Heads? Parameter Count & Big Picture", section: 7, component: "WhyEightHeads", file: "attention-computation/why-eight-heads" },
  { id: "7.14", title: "Is W_O Constant? Does It Change?", section: 7, component: "IsWOConstant", file: "attention-computation/is-w-o-constant" },
  { id: "7.15", title: "Attention Flow - Shapes at Every Step", section: 7, component: "AttentionShapes", file: "attention-computation/attention-shapes" },
  { id: "7.16", title: "The Complete Picture - In Plain English", section: 7, component: "CompletePicture", file: "attention-computation/complete-picture" },
  // Section 8: The Encoder (EncoderDecoder opens, then Add&Norm/FFN/block repeats)
  { id: "8.1", title: "Encoder & Decoder - The Two Halves", section: 8, component: "EncoderDecoder", file: "road-to-transformers/encoder-decoder" },
  { id: "8.2", title: "Add & Norm - The Stabilizer", section: 8, component: "AddNorm", file: "transformer-block/add-norm" },
  { id: "8.3", title: "FFN - The Feed-Forward Network", section: 8, component: "FeedForwardNetwork", file: "transformer-block/feed-forward-network" },
  { id: "8.4", title: "FFN - Why Word Count Doesn't Matter", section: 8, component: "FFNParallelTrick", file: "transformer-block/ffn-parallel-trick" },
  { id: "8.5", title: "Add & Norm (Again) - The Second Stabilizer", section: 8, component: "AddNormTwo", file: "transformer-block/add-norm-two" },
  { id: "8.6", title: "Nx - The Transformer Block Repeats", section: 8, component: "TransformerBlockRepeats", file: "transformer-block/transformer-block-repeats" },
  { id: "8.7", title: "Residual Connections - The Gradient Highway", section: 8, component: "ResidualHighway", file: "transformer-block/residual-highway" },
  { id: "8.8", title: "Pre-Norm vs Post-Norm", section: 8, component: "PreNormVsPostNorm", file: "transformer-block/pre-norm-vs-post-norm" },
  { id: "8.9", title: "Batch Norm vs Layer Norm", section: 8, component: "BatchNormVsLayerNorm", file: "transformer-block/batch-norm-vs-layer-norm" },
  // Section 9: The Decoder (decoder-only, causal masking, cross-attention, capstone)
  { id: "9.1", title: "Decoder-Only - How Modern LLMs Work", section: 9, component: "DecoderOnly", file: "road-to-transformers/decoder-only" },
  { id: "9.2", title: "Causal Masking - Hiding the Future", section: 9, component: "CausalMask", file: "attention-computation/causal-mask" },
  { id: "9.3", title: "Cross-Attention - The Encoder-Decoder Bridge", section: 9, component: "CrossAttention", file: "attention-computation/cross-attention" },
  { id: "9.4", title: "The Output Head - Linear + Softmax", section: 9, component: "OutputHead", file: "transformer-input/output-head" },
  { id: "9.5", title: "What is a Transformer Actually Doing?", section: 9, component: "WhatTransformerDoes", file: "transformer-input/what-transformer-does" },
  { id: "9.6", title: "Encoder-Decoder: The Training Flow", section: 9, component: "EncoderDecoderTraining", file: "encoder-decoder-diagrams/encoder-decoder-training" },
  { id: "9.7", title: "Encoder-Decoder: The Inference Flow", section: 9, component: "EncoderDecoderInference", file: "encoder-decoder-diagrams/encoder-decoder-inference" },
  // Section 10: Modern LLM Techniques
  { id: "10.1", title: "KV Cache - Why Inference is Fast", section: 10, component: "KVCache", file: "attention-computation/kv-cache" },
  {
    id: "10.2",
    title: "Grouped-Query Attention - Shrinking the KV Cache",
    section: 10,
    component: "GroupedQueryAttention",
    file: "attention-computation/grouped-query-attention",
  },
  { id: "10.3", title: "Mixture of Experts - Bigger Model, Same Compute", section: 10, component: "MixtureOfExperts", file: "modern-llm-techniques/mixture-of-experts" },
  { id: "10.4", title: "Thinking - How Reasoning Models Work", section: 10, component: "Thinking", file: "modern-llm-techniques/thinking" },
  // Section 11: Vector Databases
  { id: "11.1", title: "The Retrieval Problem", section: 11, component: "RetrievalProblem", file: "vector-foundations/retrieval-problem" },
  { id: "11.2", title: "Brute-Force kNN", section: 11, component: "BruteForceKNN", file: "vector-foundations/brute-force-knn" },
  { id: "11.3", title: "The Three-Way Tradeoff", section: 11, component: "ThreeWayTradeoff", file: "vector-foundations/three-way-tradeoff" },
  { id: "11.4", title: "Distance Metrics", section: 11, component: "DistanceMetrics", file: "vector-foundations/distance-metrics" },
  { id: "11.5", title: "The ANN Family Tree", section: 11, component: "ANNFamilyTree", file: "vector-foundations/ann-family-tree" },
  { id: "11.6", title: "IVF (Inverted File Index)", section: 11, component: "IVF", file: "vector-foundations/ivf" },
  { id: "11.7", title: "HNSW - The Small-World Intuition", section: 11, component: "HNSWIntuition", file: "vector-foundations/hnsw-intuition" },
  { id: "11.8", title: "HNSW Construction", section: 11, component: "HNSWConstruction", file: "vector-foundations/hnsw-construction" },
  { id: "11.9", title: "HNSW Search", section: 11, component: "HNSWSearch", file: "vector-foundations/hnsw-search" },
  { id: "11.10", title: "HNSW Parameters", section: 11, component: "HNSWParameters", file: "vector-foundations/hnsw-parameters" },
  { id: "11.11", title: "Vamana / DiskANN", section: 11, component: "Vamana", file: "vector-foundations/vamana" },
  { id: "11.12", title: "The Memory Wall", section: 11, component: "MemoryWall", file: "vector-compression/memory-wall" },
  { id: "11.13", title: "Scalar Quantization", section: 11, component: "ScalarQuantization", file: "vector-compression/scalar-quantization" },
  { id: "11.14", title: "Product Quantization (+ OPQ)", section: 11, component: "ProductQuantization", file: "vector-compression/product-quantization" },
  { id: "11.15", title: "Binary Quantization", section: 11, component: "BinaryQuantization", file: "vector-compression/binary-quantization" },
  { id: "11.16", title: "Matryoshka Embeddings", section: 11, component: "Matryoshka", file: "vector-compression/matryoshka" },
  { id: "11.17", title: "IVF-PQ", section: 11, component: "IVFPQ", file: "vector-compression/ivf-pq" },
  { id: "11.18", title: "HNSW + PQ", section: 11, component: "HNSWPQ", file: "vector-compression/hnsw-pq" },
  { id: "11.19", title: "The Compression Decision", section: 11, component: "CompressionDecision", file: "vector-compression/compression-decision" },
  { id: "11.20", title: "Filtering", section: 11, component: "Filtering", file: "vector-production/filtering" },
  { id: "11.21", title: "Updates & Deletes", section: 11, component: "UpdatesDeletes", file: "vector-production/updates-deletes" },
  { id: "11.22", title: "Sharding & Partitioning", section: 11, component: "Sharding", file: "vector-production/sharding" },
  { id: "11.23", title: "Replication & High Availability", section: 11, component: "Replication", file: "vector-production/replication" },
  { id: "11.24", title: "Hybrid Search", section: 11, component: "HybridSearch", file: "vector-production/hybrid-search" },
  { id: "11.25", title: "Rerankers", section: 11, component: "Rerankers", file: "vector-production/rerankers" },
  { id: "11.26", title: "Multi-vector Retrieval (ColBERT-style)", section: 11, component: "MultiVectorRetrieval", file: "vector-production/multi-vector-retrieval" },
  { id: "11.27", title: "Embedding Lifecycle & Re-embedding", section: 11, component: "EmbeddingLifecycle", file: "vector-production/embedding-lifecycle" },
  { id: "11.28", title: "Observability", section: 11, component: "Observability", file: "vector-production/observability" },
  { id: "11.29", title: "Capacity Planning & Cost Models", section: 11, component: "CapacityPlanning", file: "vector-production/capacity-planning" },
  { id: "11.30", title: "FAISS", section: 11, component: "FAISS", file: "vector-systems/faiss" },
  { id: "11.31", title: "pgvector", section: 11, component: "Pgvector", file: "vector-systems/pgvector" },
  { id: "11.32", title: "Qdrant", section: 11, component: "Qdrant", file: "vector-systems/qdrant" },
  { id: "11.33", title: "Pinecone", section: 11, component: "Pinecone", file: "vector-systems/pinecone" },
  { id: "11.34", title: "Qdrant vs Pinecone", section: 11, component: "QdrantVsPinecone", file: "vector-systems/qdrant-vs-pinecone" },
  { id: "11.35", title: "Weaviate / Milvus / Chroma", section: 11, component: "WeaviateMilvusChroma", file: "vector-systems/weaviate-milvus-chroma" },
  { id: "11.36", title: "The Decision Framework", section: 11, component: "DecisionFramework", file: "vector-systems/decision-framework" },
  // Section 12: Retrieval-Augmented Generation
  { id: "12.1", title: "Why LLMs Need Retrieval", section: 12, component: "WhyLLMsNeedRetrieval", file: "rag-foundations/why-llms-need-retrieval" },
  { id: "12.2", title: "The Naive RAG Pipeline", section: 12, component: "NaiveRAGPipeline", file: "rag-foundations/naive-rag-pipeline" },
  { id: "12.3", title: "Where Naive RAG Breaks", section: 12, component: "WhereNaiveRAGBreaks", file: "rag-foundations/where-naive-rag-breaks" },
  { id: "12.4", title: "Parsing - Raw Sources to Clean Text", section: 12, component: "ParsingExtraction", file: "rag-ingestion/parsing-extraction" },
  { id: "12.5", title: "Deduplication & Cleaning", section: 12, component: "DeduplicationCleaning", file: "rag-ingestion/deduplication-cleaning" },
  { id: "12.6", title: "Refresh & Sync Schedules", section: 12, component: "RefreshSync", file: "rag-ingestion/refresh-sync" },
  { id: "12.7", title: "Why Chunk At All + Fixed-Size Baseline", section: 12, component: "WhyChunkFixedSize", file: "rag-foundations/why-chunk-fixed-size" },
  { id: "12.8", title: "Recursive Structural Chunking", section: 12, component: "RecursiveStructuralChunking", file: "rag-foundations/recursive-structural-chunking" },
  { id: "12.9", title: "Semantic Chunking", section: 12, component: "SemanticChunking", file: "rag-foundations/semantic-chunking" },
  { id: "12.10", title: "Late Chunking (Jina 2024)", section: 12, component: "LateChunking", file: "rag-foundations/late-chunking" },
  { id: "12.11", title: "Hierarchical / Parent-Child Chunking", section: 12, component: "HierarchicalChunking", file: "rag-foundations/hierarchical-chunking" },
  { id: "12.12", title: "Contextual Retrieval (Anthropic 2024)", section: 12, component: "ContextualRetrieval", file: "rag-foundations/contextual-retrieval" },
  { id: "12.13", title: "The Chunking Decision", section: 12, component: "ChunkingDecision", file: "rag-foundations/chunking-decision" },
  // Section 12 Act 4: Embed & Index Choices for RAG
  { id: "12.14", title: "Picking an Embedding Model", section: 12, component: "EmbeddingModelChoice", file: "rag-retrieval/embedding-model-choice" },
  { id: "12.15", title: "Domain Adaptation - Fine-Tuning Embeddings", section: 12, component: "DomainAdaptation", file: "rag-retrieval/domain-adaptation" },
  { id: "12.16", title: "Hybrid Retrieval for RAG", section: 12, component: "HybridForRAG", file: "rag-retrieval/hybrid-for-rag" },
  { id: "12.17", title: "The Reranker Cascade", section: 12, component: "RerankerCascade", file: "rag-retrieval/reranker-cascade" },
  // Section 12 Act 5: Query Transformation
  { id: "12.18", title: "Why Transform Queries", section: 12, component: "WhyTransformQueries", file: "rag-retrieval/why-transform-queries" },
  { id: "12.19", title: "HyDE - Hypothetical Document Embeddings", section: 12, component: "HyDE", file: "rag-retrieval/hy-de" },
  { id: "12.20", title: "Multi-Query Expansion", section: 12, component: "MultiQueryExpansion", file: "rag-retrieval/multi-query-expansion" },
  { id: "12.21", title: "Query Routing & Decomposition", section: 12, component: "QueryRoutingDecomposition", file: "rag-retrieval/query-routing-decomposition" },
  // Section 12 Acts 6+7: Context & Generation, Advanced Retrieval Patterns
  { id: "12.22", title: "Context Packing", section: 12, component: "ContextPacking", file: "rag-generation/context-packing" },
  { id: "12.23", title: "The Lost-in-the-Middle Problem", section: 12, component: "LostInTheMiddle", file: "rag-generation/lost-in-the-middle" },
  { id: "12.24", title: "Citations, Refusal & Groundedness", section: 12, component: "CitationsRefusal", file: "rag-generation/citations-refusal" },
  { id: "12.25", title: "Multi-Hop Retrieval", section: 12, component: "MultiHopRetrieval", file: "rag-generation/multi-hop-retrieval" },
  { id: "12.26", title: "Self-RAG", section: 12, component: "SelfRAG", file: "rag-generation/self-rag" },
  { id: "12.27", title: "CRAG - Corrective RAG", section: 12, component: "CorrectiveRAG", file: "rag-generation/corrective-rag" },
  { id: "12.28", title: "GraphRAG (Microsoft 2024)", section: 12, component: "GraphRAG", file: "rag-generation/graph-rag" },
  { id: "12.29", title: "Tool-Augmented & Agentic RAG", section: 12, component: "AgenticRAG", file: "rag-generation/agentic-rag" },
  { id: "12.30", title: "Long-Context vs RAG", section: 12, component: "LongContextVsRAG", file: "rag-generation/long-context-vs-rag" },
  // Section 12 Act 8: Evaluation
  { id: "12.31", title: "The RAG Eval Triangle", section: 12, component: "RAGEvalTriangle", file: "rag-evaluation/rag-eval-triangle" },
  { id: "12.32", title: "LLM-as-Judge", section: 12, component: "LLMAsJudge", file: "rag-evaluation/llm-as-judge" },
  { id: "12.33", title: "RAGAS Metrics", section: 12, component: "RAGASMetrics", file: "rag-evaluation/ragas-metrics" },
  { id: "12.34", title: "Golden Datasets", section: 12, component: "GoldenDatasets", file: "rag-evaluation/golden-datasets" },
  { id: "12.35", title: "Online Eval & A/B Testing", section: 12, component: "OnlineEvalABTesting", file: "rag-evaluation/online-eval-ab-testing" },
  // Section 12 Act 9: Production Operations
  { id: "12.36", title: "Caching - Prompt + Semantic", section: 12, component: "Caching", file: "rag-production/caching" },
  { id: "12.37", title: "Cost Models", section: 12, component: "CostModels", file: "rag-production/cost-models" },
  { id: "12.38", title: "Observability & Tracing", section: 12, component: "ObservabilityTracing", file: "rag-production/observability-tracing" },
  { id: "12.39", title: "Hallucination Detection & Drift", section: 12, component: "HallucinationDrift", file: "rag-production/hallucination-drift" },
  { id: "12.40", title: "Framework Choice", section: 12, component: "FrameworkChoice", file: "rag-production/framework-choice" },
  // Section 12 Act 10: Decision Framework + Capstone
  {
    id: "12.41",
    title: "The Complete RAG Decision Framework + Capstone",
    section: 12,
    component: "RAGDecisionFrameworkCapstone",
    file: "rag-production/rag-decision-framework-capstone",
  },
  // Section 13: AI Agents
  { id: "13.1", title: "Anatomy of an LLM Call", section: 13, component: "AnatomyOfLlmCall", file: "agent-prompting/anatomy-of-llm-call" },
  { id: "13.2", title: "System Prompts - The Role Contract", section: 13, component: "SystemPromptContract", file: "agent-prompting/system-prompt-contract" },
  { id: "13.3", title: "Few-Shot + Structured Output", section: 13, component: "FewShotStructuredOutput", file: "agent-prompting/few-shot-structured-output" },
  {
    id: "13.4",
    title: "Chain of Thought + Self-Consistency",
    section: 13,
    component: "ChainOfThoughtSelfConsistency",
    file: "agent-prompting/chain-of-thought-self-consistency",
  },
  { id: "13.5", title: "Prompt vs Fine-Tune vs RAG vs Agent", section: 13, component: "PromptVsTuneVsRagVsAgent", file: "agent-prompting/prompt-vs-tune-vs-rag-vs-agent" },
  { id: "13.6", title: "Context Engineering", section: 13, component: "ContextEngineering", file: "agent-prompting/context-engineering" },
  { id: "13.7", title: "Tool Use - LLM as Orchestrator", section: 13, component: "ToolUseAsBridge", file: "agent-tools/tool-use-as-bridge" },
  { id: "13.8", title: "JSON Schemas + Tool Descriptions", section: 13, component: "JsonSchemaForTools", file: "agent-tools/json-schema-for-tools" },
  { id: "13.9", title: "Tool Call Lifecycle", section: 13, component: "ToolCallLifecycle", file: "agent-tools/tool-call-lifecycle" },
  { id: "13.10", title: "Parallel Tools + Tool Choice", section: 13, component: "ParallelToolsAndChoice", file: "agent-tools/parallel-tools-and-choice" },
  { id: "13.11", title: "Tool Errors, Retries, Validation", section: 13, component: "ToolErrorsRetries", file: "agent-tools/tool-errors-retries" },
  { id: "13.12", title: "Why Protocols?", section: 13, component: "WhyProtocols", file: "agent-tools/why-protocols" },
  { id: "13.13", title: "MCP Architecture", section: 13, component: "McpArchitecture", file: "agent-tools/mcp-architecture" },
  { id: "13.14", title: "MCP Primitives - Tools, Resources, Prompts", section: 13, component: "McpPrimitives", file: "agent-tools/mcp-primitives" },
  { id: "13.15", title: "Building an MCP Server", section: 13, component: "BuildingMcpServer", file: "agent-tools/building-mcp-server" },
  { id: "13.16", title: "MCP Security", section: 13, component: "McpSecurity", file: "agent-tools/mcp-security" },
  { id: "13.17", title: "A2A - Agent-to-Agent Protocol", section: 13, component: "A2AProtocol", file: "agent-tools/a2a-protocol" },
  { id: "13.18", title: "Workflow vs Agent", section: 13, component: "WorkflowVsAgent", file: "agent-loops/workflow-vs-agent" },
  { id: "13.19", title: "Workflow Primitives - Chaining, Routing, Parallelization", section: 13, component: "WorkflowPrimitives", file: "agent-loops/workflow-primitives" },
  { id: "13.20", title: "The Agent Loop", section: 13, component: "AgentLoop", file: "agent-loops/agent-loop" },
  { id: "13.21", title: "ReAct Pattern", section: 13, component: "ReActPattern", file: "agent-loops/re-act-pattern" },
  { id: "13.22", title: "Plan-Execute + Reflection", section: 13, component: "PlanExecuteReflect", file: "agent-loops/plan-execute-reflect" },
  { id: "13.23", title: "Loop Termination", section: 13, component: "LoopTermination", file: "agent-loops/loop-termination" },
  { id: "13.24", title: "Memory Taxonomy - Short vs Long", section: 13, component: "MemoryTaxonomy", file: "agent-loops/memory-taxonomy" },
  { id: "13.25", title: "Working Memory - The Scratchpad", section: 13, component: "WorkingMemory", file: "agent-loops/working-memory" },
  { id: "13.26", title: "Episodic Memory - Past Events", section: 13, component: "EpisodicMemory", file: "agent-loops/episodic-memory" },
  { id: "13.27", title: "Semantic Memory - Learned Facts", section: 13, component: "SemanticMemory", file: "agent-loops/semantic-memory" },
  { id: "13.28", title: "Procedural Memory - Learned Skills", section: 13, component: "ProceduralMemory", file: "agent-loops/procedural-memory" },
  { id: "13.29", title: "Summary Memory + Context Window Management", section: 13, component: "SummaryAndContextMgmt", file: "agent-loops/summary-and-context-mgmt" },
  { id: "13.30", title: "Why Multi-Agent?", section: 13, component: "WhyMultiAgent", file: "multi-agent/why-multi-agent" },
  { id: "13.31", title: "Orchestrator-Worker", section: 13, component: "OrchestratorWorker", file: "multi-agent/orchestrator-worker" },
  { id: "13.32", title: "Supervisor / Hierarchical", section: 13, component: "SupervisorHierarchy", file: "multi-agent/supervisor-hierarchy" },
  { id: "13.33", title: "Hand-Offs", section: 13, component: "AgentHandoffs", file: "multi-agent/agent-handoffs" },
  { id: "13.34", title: "Critic / Debate / Reflection-as-Multi-Agent", section: 13, component: "CriticDebate", file: "multi-agent/critic-debate" },
  { id: "13.35", title: "Multi-Agent Failure Modes", section: 13, component: "MultiAgentFailures", file: "multi-agent/multi-agent-failures" },
  { id: "13.36", title: "Agentic RAG", section: 13, component: "AgenticRag", file: "multi-agent/agentic-rag" },
  { id: "13.37", title: "Why Eval Agents Differently", section: 13, component: "WhyEvalAgents", file: "agent-evals/why-eval-agents" },
  { id: "13.38", title: "Eval Dimensions", section: 13, component: "EvalDimensions", file: "agent-evals/eval-dimensions" },
  { id: "13.39", title: "LLM-as-Judge", section: 13, component: "LlmAsJudge", file: "agent-evals/llm-as-judge" },
  { id: "13.40", title: "Trace Evals", section: 13, component: "TraceEvals", file: "agent-evals/trace-evals" },
  { id: "13.41", title: "Eval Sets + Continuous Eval", section: 13, component: "EvalSetsContinuous", file: "agent-evals/eval-sets-continuous" },
  { id: "13.42", title: "Observability & Tracing", section: 13, component: "AgentObservabilityTracing", file: "agent-production/agent-observability-tracing" },
  { id: "13.43", title: "Cost Control", section: 13, component: "CostControl", file: "agent-production/cost-control" },
  { id: "13.44", title: "Latency Optimization", section: 13, component: "LatencyOptimization", file: "agent-production/latency-optimization" },
  { id: "13.45", title: "Guardrails", section: 13, component: "Guardrails", file: "agent-production/guardrails" },
  { id: "13.46", title: "Prompt Injection Defenses", section: 13, component: "PromptInjectionDefenses", file: "agent-production/prompt-injection-defenses" },
  { id: "13.47", title: "Tool Security", section: 13, component: "ToolSecurity", file: "agent-production/tool-security" },
  { id: "13.48", title: "LangGraph", section: 13, component: "LangGraphFramework", file: "agent-production/lang-graph-framework" },
  { id: "13.49", title: "CrewAI / AutoGen", section: 13, component: "CrewAiAutoGen", file: "agent-production/crew-ai-auto-gen" },
  {
    id: "13.50",
    title: "Claude Agent SDK + OpenAI Agents",
    section: 13,
    component: "VendorSdks",
    file: "agent-production/vendor-sdks",
  },
  { id: "13.51", title: "Custom / No-Framework", section: 13, component: "CustomNoFramework", file: "agent-production/custom-no-framework" },
  {
    id: "13.52",
    title: "The Complete Agent Decision Framework",
    section: 13,
    component: "AgentDecisionFramework",
    file: "agent-production/agent-decision-framework",
  },
];

export const sectionNames = {
  0: "Overview",
  1: "Neural Network Foundations",
  2: "How LLMs Actually Train",
  3: "Scaling & Modern Techniques",
  4: "The Road to Transformers",
  5: "Transformer Input Pipeline",
  6: "Attention - Understanding Q, K, V",
  7: "Attention - The Full Computation",
  8: "The Encoder",
  9: "The Decoder",
  10: "Modern LLM Techniques",
  11: "Vector Databases",
  12: "Retrieval-Augmented Generation",
  13: "AI Agents",
};

// Section colors (one per section, used in progress bar, TOC, etc.)
export const sectionColors = {
  1: "#ff6b6b",
  2: "#00b8d4",
  3: "#ffd740",
  4: "#a78bfa",
  5: "#ffab40",
  6: "#00e676",
  7: "#e040fb",
  8: "#42a5f5",
  9: "#ef5350",
  10: "#26a69a",
  11: "#f06292",
  12: "#7c4dff",
  13: "#00838f",
};

// Colors
export const C = {
  bg: "#08080d",
  card: "rgba(255,255,255,0.025)",
  border: "rgba(255,255,255,0.07)",
  dim: "rgba(255,255,255,0.35)",
  mid: "rgba(255,255,255,0.55)",
  bright: "rgba(255,255,255,0.85)",
  red: "#ff6b6b",
  purple: "#a78bfa",
  green: "#00e676",
  cyan: "#00b8d4",
  yellow: "#ffd740",
  pink: "#e040fb",
  orange: "#ffab40",
  blue: "#42a5f5",
  indigo: "#5c6bc0",
  teal: "#26c6da",
  amber: "#ffc107",
};

// Validate config - extracted for testability
export function validateConfig(chapterList) {
  const errors = [];
  const ids = chapterList.map((c) => c.id);
  const dupes = ids.filter((id, i) => ids.indexOf(id) !== i);
  if (dupes.length) errors.push(`Duplicate chapter IDs: ${dupes.join(", ")}`);
  chapterList.forEach((c) => {
    if (c.component && !c.id) errors.push(`Chapter missing id: ${c.component}`);
    if (!c.component) errors.push(`Chapter missing component: id=${c.id}`);
  });
  return errors;
}

// Config validation runs via tests (see config.test.js) using validateConfig().
