export const chapters = [
  { id: "0", title: "Table of Contents", section: 0, component: "TOC", file: "table-of-contents/toc", slug: "table-of-contents/toc" },
  // Section 1: Neural Network Foundations
  {
    id: "1.1",
    title: "What is a Neural Network?",
    section: 1,
    component: "WhatIsNN",
    file: "neural-foundations/what-is-nn",
    slug: "neural-foundations/what-is-nn",
  },
  {
    id: "1.2",
    title: "Inside a Single Neuron",
    section: 1,
    component: "InsideNeuron",
    file: "neural-foundations/inside-neuron",
    slug: "neural-foundations/inside-neuron",
  },
  {
    id: "1.3",
    title: "What is a Layer?",
    section: 1,
    component: "WhatIsLayer",
    file: "neural-foundations/what-is-layer",
    slug: "neural-foundations/what-is-layer",
  },
  {
    id: "1.4",
    title: "Weights & Biases - The Knobs",
    section: 1,
    component: "WeightsBiases",
    file: "neural-foundations/weights-biases",
    slug: "neural-foundations/weights-biases",
  },
  {
    id: "1.5",
    title: "Why Linear Isn't Enough",
    section: 1,
    component: "WhyLinear",
    file: "neural-foundations/why-linear",
    slug: "neural-foundations/why-linear",
  },
  {
    id: "1.6",
    title: "Activation (ReLU) - Why Layers Need a Bend",
    section: 1,
    component: "ReLU",
    file: "neural-foundations/re-lu",
    slug: "neural-foundations/re-lu",
  },
  {
    id: "1.7",
    title: "The Forward Pass - Full Example",
    section: 1,
    component: "ForwardPass",
    file: "neural-foundations/forward-pass",
    slug: "neural-foundations/forward-pass",
  },
  {
    id: "2.1",
    title: "Loss - How Wrong Were We?",
    section: 2,
    component: "LossFunction",
    file: "neural-foundations/loss-function",
    slug: "neural-foundations/loss-function",
  },
  {
    id: "2.2",
    title: "Learning - What Does It Mean?",
    section: 2,
    component: "WhatIsLearning",
    file: "neural-foundations/what-is-learning",
    slug: "neural-foundations/what-is-learning",
  },
  {
    id: "2.3",
    title: "Derivatives - The Core Intuition",
    section: 2,
    component: "Derivatives",
    file: "neural-foundations/derivatives",
    slug: "neural-foundations/derivatives",
  },
  {
    id: "2.4",
    title: "The Backward Pass - The Chain Rule",
    section: 2,
    component: "BackwardPass",
    file: "neural-foundations/backward-pass",
    slug: "neural-foundations/backward-pass",
  },
  {
    id: "2.5",
    title: "Gradient Descent - Fixing the Weights",
    section: 2,
    component: "GradientDescent",
    file: "neural-foundations/gradient-descent",
    slug: "neural-foundations/gradient-descent",
  },
  {
    id: "2.6",
    title: "Backprop Through the Real Network",
    section: 2,
    component: "BackpropRealNetwork",
    file: "neural-foundations/backprop-real-network",
    slug: "neural-foundations/backprop-real-network",
  },
  {
    id: "2.7",
    title: "Gradients in Action - The Full Training Loop",
    section: 2,
    component: "GradientsInAction",
    file: "neural-foundations/gradients-in-action",
    slug: "neural-foundations/gradients-in-action",
  },
  {
    id: "2.8",
    title: "Why Deep Backprop Gets Hard",
    section: 2,
    component: "WhyBackpropHard",
    file: "neural-foundations/why-backprop-hard",
    slug: "neural-foundations/why-backprop-hard",
  },
  {
    id: "3.1",
    title: "Vectors - Numbers That Travel Together",
    section: 3,
    component: "Vectors",
    file: "neural-foundations/vectors",
    slug: "neural-foundations/vectors",
  },
  {
    id: "3.2",
    title: "The Dot Product - How Vectors Compare",
    section: 3,
    component: "DotProductIntro",
    file: "neural-foundations/dot-product-intro",
    slug: "neural-foundations/dot-product-intro",
  },
  {
    id: "3.3",
    title: "Matrices - Grids That Transform Vectors",
    section: 3,
    component: "Matrices",
    file: "neural-foundations/matrices",
    slug: "neural-foundations/matrices",
  },
  {
    id: "3.4",
    title: "A Layer is Matrix Multiplication",
    section: 3,
    component: "LayerIsMatMul",
    file: "neural-foundations/layer-is-mat-mul",
    slug: "neural-foundations/layer-is-mat-mul",
  },
  {
    id: "3.5",
    title: "Activation Functions - The Full Picture",
    section: 3,
    component: "ActivationFunctions",
    file: "neural-foundations/activation-functions",
    slug: "neural-foundations/activation-functions",
  },
  {
    id: "4.1",
    title: 'What "Deep" Really Means',
    section: 4,
    component: "WhatDeepMeans",
    file: "neural-foundations/what-deep-means",
    slug: "neural-foundations/what-deep-means",
  },
  {
    id: "4.2",
    title: "Same Building Blocks, Different Shapes",
    section: 4,
    component: "SameBuildingBlocks",
    file: "neural-foundations/same-building-blocks",
    slug: "neural-foundations/same-building-blocks",
  },
  {
    id: "4.3",
    title: "Dropout - The Regularization Trick",
    section: 4,
    component: "Dropout",
    file: "neural-foundations/dropout",
    slug: "neural-foundations/dropout",
  },
  {
    id: "4.4",
    title: "Adam - The Real Optimizer",
    section: 4,
    component: "AdamOptimizer",
    file: "neural-foundations/adam-optimizer",
    slug: "neural-foundations/adam-optimizer",
  },
  {
    id: "4.5",
    title: "Learning Rate Warmup & Decay",
    section: 4,
    component: "LRWarmupDecay",
    file: "neural-foundations/lr-warmup-decay",
    slug: "neural-foundations/lr-warmup-decay",
  },
  {
    id: "4.6",
    title: "Weight Initialization - How Random?",
    section: 4,
    component: "WeightInit",
    file: "neural-foundations/weight-init",
    slug: "neural-foundations/weight-init",
  },
  // Section 2: How LLMs Actually Train (reordered: output/generation before fine-tuning)
  {
    id: "5.1",
    title: "Tokenization - From Words to Numbers",
    section: 5,
    component: "Tokenization",
    file: "llm-training/tokenization",
    slug: "llm-training/tokenization",
  },
  {
    id: "5.2",
    title: "Self-Supervised Learning - How GPT Trains",
    section: 5,
    component: "SelfSupervised",
    file: "llm-training/self-supervised",
    slug: "llm-training/self-supervised",
  },
  {
    id: "5.3",
    title: "Cross-Entropy Loss - The LLM Score",
    section: 5,
    component: "CrossEntropy",
    file: "llm-training/cross-entropy",
    slug: "llm-training/cross-entropy",
  },
  {
    id: "5.4",
    title: "The Neural Network in Action",
    section: 5,
    component: "NNInAction",
    file: "llm-training/nn-in-action",
    slug: "llm-training/nn-in-action",
  },
  {
    id: "5.5",
    title: "The Output Layer - From Hidden State to Words",
    section: 5,
    component: "OutputLayer",
    file: "llm-training/output-layer",
    slug: "llm-training/output-layer",
  },
  {
    id: "5.6",
    title: "Autoregressive Generation - One Token at a Time",
    section: 5,
    component: "AutoregressiveGeneration",
    file: "llm-training/autoregressive-generation",
    slug: "llm-training/autoregressive-generation",
  },
  { id: "5.7", title: "Supervised Fine-Tuning (SFT)", section: 5, component: "SFT", file: "llm-training/sft", slug: "llm-training/sft" },
  { id: "5.8", title: "RLHF - Making AI Helpful & Safe", section: 5, component: "RLHF", file: "llm-training/rlhf", slug: "llm-training/rlhf" },
  { id: "5.9", title: "DPO - Simpler Alignment", section: 5, component: "DPO", file: "llm-training/dpo", slug: "llm-training/dpo" },
  {
    id: "5.10",
    title: "Tokenizer Deep Dive - BPE, WordPiece, SentencePiece",
    section: 5,
    component: "TokenizerDeepDive",
    file: "llm-training/tokenizer-deep-dive",
    slug: "llm-training/tokenizer-deep-dive",
  },
  // Section 3: Scaling & Modern Techniques (BatchTraining added)
  {
    id: "6.1",
    title: "Scaling Laws - Why Bigger Models Win",
    section: 6,
    component: "ScalingLaws",
    file: "scaling/scaling-laws",
    slug: "scaling/scaling-laws",
  },
  {
    id: "6.2",
    title: "Parameters at Scale",
    section: 6,
    component: "ParametersAtScale",
    file: "scaling/parameters-at-scale",
    slug: "scaling/parameters-at-scale",
  },
  {
    id: "6.3",
    title: "Batch Training - Why Not One Example at a Time?",
    section: 6,
    component: "BatchTraining",
    file: "llm-training/batch-training",
    slug: "llm-training/batch-training",
  },
  {
    id: "6.4",
    title: "Knowledge Distillation - Teacher to Student",
    section: 6,
    component: "Distillation",
    file: "scaling/distillation",
    slug: "scaling/distillation",
  },
  { id: "6.5", title: "CLIP - Teaching AI to See & Read", section: 6, component: "CLIP", file: "scaling/clip", slug: "scaling/clip" },
  {
    id: "6.6",
    title: "The Complete Training Pipeline",
    section: 6,
    component: "TrainingPipeline",
    file: "scaling/training-pipeline",
    slug: "scaling/training-pipeline",
  },
  // Section 4: The Road to Transformers (trimmed: encoder/decoder moved to Sections 8-9)
  { id: "7.1", title: "CNN", section: 7, component: "CNN", file: "road-to-transformers/cnn", slug: "road-to-transformers/cnn" },
  { id: "7.2", title: "RNN", section: 7, component: "RNN", file: "road-to-transformers/rnn", slug: "road-to-transformers/rnn" },
  { id: "7.3", title: "RNN's Fatal Flaws", section: 7, component: "RNNFlaws", file: "road-to-transformers/rnn-flaws", slug: "road-to-transformers/rnn-flaws" },
  {
    id: "7.4",
    title: "The Transformer Arrives",
    section: 7,
    component: "TransformerArrives",
    file: "road-to-transformers/transformer-arrives",
    slug: "road-to-transformers/transformer-arrives",
  },
  // Section 5: Transformer Input Pipeline (trimmed: WhatTransformerDoes moved to Section 9)
  {
    id: "8.1",
    title: "The Full Architecture",
    section: 8,
    component: "FullArchitecture",
    file: "transformer-input/full-architecture",
    slug: "transformer-input/full-architecture",
  },
  { id: "8.2", title: "Zoom: Embeddings", section: 8, component: "Embeddings", file: "transformer-input/embeddings", slug: "transformer-input/embeddings" },
  {
    id: "8.3",
    title: "Positional Encoding - The Problem",
    section: 8,
    component: "PosEncodingProblem",
    file: "transformer-input/pos-encoding-problem",
    slug: "transformer-input/pos-encoding-problem",
  },
  {
    id: "8.4",
    title: "Positional Encoding - The Formula",
    section: 8,
    component: "PosEncodingFormula",
    file: "transformer-input/pos-encoding-formula",
    slug: "transformer-input/pos-encoding-formula",
  },
  {
    id: "8.5",
    title: "Positional Encoding - Computing Positions",
    section: 8,
    component: "PosEncodingCompute",
    file: "transformer-input/pos-encoding-compute",
    slug: "transformer-input/pos-encoding-compute",
  },
  {
    id: "8.6",
    title: "Positional Encoding - Fast vs Slow",
    section: 8,
    component: "PosEncodingFastSlow",
    file: "transformer-input/pos-encoding-fast-slow",
    slug: "transformer-input/pos-encoding-fast-slow",
  },
  {
    id: "8.7",
    title: "Positional Encoding - Final Addition",
    section: 8,
    component: "PosEncodingFinal",
    file: "transformer-input/pos-encoding-final",
    slug: "transformer-input/pos-encoding-final",
  },
  {
    id: "8.8",
    title: "Positional Encoding - The Heatmap",
    section: 8,
    component: "PosEncodingHeatmap",
    file: "transformer-input/pos-encoding-heatmap",
    slug: "transformer-input/pos-encoding-heatmap",
  },
  {
    id: "8.9",
    title: "RoPE - Rotary Position Embeddings",
    section: 8,
    component: "RoPE",
    file: "transformer-input/ro-pe",
    slug: "transformer-input/ro-pe",
  },
  // Section 6: Attention - Understanding Q, K, V
  {
    id: "9.1",
    title: "The Problem - Context is Everything",
    section: 9,
    component: "ContextProblem",
    file: "attention-qkv/context-problem",
    slug: "attention-qkv/context-problem",
  },
  {
    id: "9.2",
    title: "How Does a Word Look At Others?",
    section: 9,
    component: "WordLookup",
    file: "attention-qkv/word-lookup",
    slug: "attention-qkv/word-lookup",
  },
  {
    id: "9.3",
    title: "The Dot Product - Measuring Similarity",
    section: 9,
    component: "DotProduct",
    file: "attention-qkv/dot-product",
    slug: "attention-qkv/dot-product",
  },
  {
    id: "9.4",
    title: "Why Not Dot Product Embeddings Directly?",
    section: 9,
    component: "WhyNotDirectDot",
    file: "attention-qkv/why-not-direct-dot",
    slug: "attention-qkv/why-not-direct-dot",
  },
  {
    id: "9.5",
    title: "Q, K, V - The Classroom Analogy",
    section: 9,
    component: "QKVClassroom",
    file: "attention-qkv/qkv-classroom",
    slug: "attention-qkv/qkv-classroom",
  },
  {
    id: "9.6",
    title: "Every Word is Both Asker and Answerer",
    section: 9,
    component: "AskerAnswerer",
    file: "attention-qkv/asker-answerer",
    slug: "attention-qkv/asker-answerer",
  },
  {
    id: "9.7",
    title: "Why Can\'t Key and Value Be the Same?",
    section: 9,
    component: "WhyKVDifferent",
    file: "attention-qkv/why-kv-different",
    slug: "attention-qkv/why-kv-different",
  },
  {
    id: "9.8",
    title: "The Google Search Analogy",
    section: 9,
    component: "GoogleAnalogy",
    file: "attention-qkv/google-analogy",
    slug: "attention-qkv/google-analogy",
  },
  {
    id: "9.9",
    title: "How Are Q, K, V Created?",
    section: 9,
    component: "HowQKVCreated",
    file: "attention-qkv/how-qkv-created",
    slug: "attention-qkv/how-qkv-created",
  },
  {
    id: "9.10",
    title: "Shapes - Why Q is Smaller Than the Embedding",
    section: 9,
    component: "QKVShapes",
    file: "attention-qkv/qkv-shapes",
    slug: "attention-qkv/qkv-shapes",
  },
  {
    id: "9.11",
    title: "W Matrices - Learned During Training",
    section: 9,
    component: "WMatrices",
    file: "attention-qkv/w-matrices",
    slug: "attention-qkv/w-matrices",
  },
  {
    id: "9.12",
    title: "Tracing a Complete Example",
    section: 9,
    component: "TracingExample",
    file: "attention-qkv/tracing-example",
    slug: "attention-qkv/tracing-example",
  },
  // Section 7: Attention - The Full Computation (CausalMask/CrossAttention moved to Section 9)
  {
    id: "10.1",
    title: "Step 1 - Compute Q, K, V for Every Word",
    section: 10,
    component: "ComputeQKV",
    file: "attention-computation/compute-qkv",
    slug: "attention-computation/compute-qkv",
  },
  {
    id: "10.2",
    title: "Step 2 - Attention Scores (Dot Products)",
    section: 10,
    component: "AttentionScores",
    file: "attention-computation/attention-scores",
    slug: "attention-computation/attention-scores",
  },
  {
    id: "10.3",
    title: "Why K Transpose? - Making the Shapes Fit",
    section: 10,
    component: "KTranspose",
    file: "attention-computation/k-transpose",
    slug: "attention-computation/k-transpose",
  },
  {
    id: "10.4",
    title: "Why Do We Need Softmax?",
    section: 10,
    component: "WhySoftmax",
    file: "attention-computation/why-softmax",
    slug: "attention-computation/why-softmax",
  },
  {
    id: "10.5",
    title: "Step 3 - Scale by \u221Ad_k",
    section: 10,
    component: "ScaleByRootDk",
    file: "attention-computation/scale-by-root-dk",
    slug: "attention-computation/scale-by-root-dk",
  },
  {
    id: "10.6",
    title: "Step 4 - Softmax \u2192 Probabilities",
    section: 10,
    component: "SoftmaxProbs",
    file: "attention-computation/softmax-probs",
    slug: "attention-computation/softmax-probs",
  },
  {
    id: "10.7",
    title: "Step 5 - Weighted Sum of Values",
    section: 10,
    component: "WeightedSum",
    file: "attention-computation/weighted-sum",
    slug: "attention-computation/weighted-sum",
  },
  {
    id: "10.8",
    title: "The Full Formula",
    section: 10,
    component: "FullFormula",
    file: "attention-computation/full-formula",
    slug: "attention-computation/full-formula",
  },
  {
    id: "11.1",
    title: "Why Multi-Head? - The Compromise Problem",
    section: 11,
    component: "WhyMultiHead",
    file: "attention-computation/why-multi-head",
    slug: "attention-computation/why-multi-head",
  },
  {
    id: "11.2",
    title: "The Split - How 8 Heads Work",
    section: 11,
    component: "HeadSplit",
    file: "attention-computation/head-split",
    slug: "attention-computation/head-split",
  },
  {
    id: "11.3",
    title: "Inside Each Head - Full Attention in 64 Dims",
    section: 11,
    component: "InsideEachHead",
    file: "attention-computation/inside-each-head",
    slug: "attention-computation/inside-each-head",
  },
  {
    id: "11.4",
    title: "Concat + W_O - Blending All Heads",
    section: 11,
    component: "ConcatWO",
    file: "attention-computation/concat-wo",
    slug: "attention-computation/concat-wo",
  },
  {
    id: "11.5",
    title: "Why 8 Heads? Parameter Count & Big Picture",
    section: 11,
    component: "WhyEightHeads",
    file: "attention-computation/why-eight-heads",
    slug: "attention-computation/why-eight-heads",
  },
  {
    id: "11.6",
    title: "Is W_O Constant? Does It Change?",
    section: 11,
    component: "IsWOConstant",
    file: "attention-computation/is-wo-constant",
    slug: "attention-computation/is-wo-constant",
  },
  {
    id: "11.7",
    title: "Attention Flow - Shapes at Every Step",
    section: 11,
    component: "AttentionShapes",
    file: "attention-computation/attention-shapes",
    slug: "attention-computation/attention-shapes",
  },
  {
    id: "11.8",
    title: "The Complete Picture - In Plain English",
    section: 11,
    component: "CompletePicture",
    file: "attention-computation/complete-picture",
    slug: "attention-computation/complete-picture",
  },
  // Section 8: The Encoder (EncoderDecoder opens, then Add&Norm/FFN/block repeats)
  {
    id: "12.1",
    title: "Encoder & Decoder - The Two Halves",
    section: 12,
    component: "EncoderDecoder",
    file: "road-to-transformers/encoder-decoder",
    slug: "road-to-transformers/encoder-decoder",
  },
  {
    id: "12.2",
    title: "Add & Norm - The Stabilizer",
    section: 12,
    component: "AddNorm",
    file: "transformer-block/add-norm",
    slug: "transformer-block/add-norm",
  },
  {
    id: "12.3",
    title: "FFN - The Feed-Forward Network",
    section: 12,
    component: "FeedForwardNetwork",
    file: "transformer-block/feed-forward-network",
    slug: "transformer-block/feed-forward-network",
  },
  {
    id: "12.4",
    title: "FFN - Why Word Count Doesn't Matter",
    section: 12,
    component: "FFNParallelTrick",
    file: "transformer-block/ffn-parallel-trick",
    slug: "transformer-block/ffn-parallel-trick",
  },
  {
    id: "12.5",
    title: "Add & Norm (Again) - The Second Stabilizer",
    section: 12,
    component: "AddNormTwo",
    file: "transformer-block/add-norm-two",
    slug: "transformer-block/add-norm-two",
  },
  {
    id: "12.6",
    title: "Nx - The Transformer Block Repeats",
    section: 12,
    component: "TransformerBlockRepeats",
    file: "transformer-block/transformer-block-repeats",
    slug: "transformer-block/transformer-block-repeats",
  },
  {
    id: "12.7",
    title: "Residual Connections - The Gradient Highway",
    section: 12,
    component: "ResidualHighway",
    file: "transformer-block/residual-highway",
    slug: "transformer-block/residual-highway",
  },
  {
    id: "12.8",
    title: "Pre-Norm vs Post-Norm",
    section: 12,
    component: "PreNormVsPostNorm",
    file: "transformer-block/pre-norm-vs-post-norm",
    slug: "transformer-block/pre-norm-vs-post-norm",
  },
  {
    id: "12.9",
    title: "Batch Norm vs Layer Norm",
    section: 12,
    component: "BatchNormVsLayerNorm",
    file: "transformer-block/batch-norm-vs-layer-norm",
    slug: "transformer-block/batch-norm-vs-layer-norm",
  },
  // Section 9: The Decoder (decoder-only, causal masking, cross-attention, capstone)
  {
    id: "13.1",
    title: "Decoder-Only - How Modern LLMs Work",
    section: 13,
    component: "DecoderOnly",
    file: "road-to-transformers/decoder-only",
    slug: "road-to-transformers/decoder-only",
  },
  {
    id: "13.2",
    title: "Causal Masking - Hiding the Future",
    section: 13,
    component: "CausalMask",
    file: "attention-computation/causal-mask",
    slug: "attention-computation/causal-mask",
  },
  {
    id: "13.3",
    title: "Cross-Attention - The Encoder-Decoder Bridge",
    section: 13,
    component: "CrossAttention",
    file: "attention-computation/cross-attention",
    slug: "attention-computation/cross-attention",
  },
  {
    id: "13.4",
    title: "The Output Head - Linear + Softmax",
    section: 13,
    component: "OutputHead",
    file: "transformer-input/output-head",
    slug: "transformer-input/output-head",
  },
  {
    id: "13.5",
    title: "What is a Transformer Actually Doing?",
    section: 13,
    component: "WhatTransformerDoes",
    file: "transformer-input/what-transformer-does",
    slug: "transformer-input/what-transformer-does",
  },
  {
    id: "13.6",
    title: "Encoder-Decoder: The Training Flow",
    section: 13,
    component: "EncoderDecoderTraining",
    file: "encoder-decoder-diagrams/encoder-decoder-training",
    slug: "encoder-decoder-diagrams/encoder-decoder-training",
  },
  {
    id: "13.7",
    title: "Encoder-Decoder: The Inference Flow",
    section: 13,
    component: "EncoderDecoderInference",
    file: "encoder-decoder-diagrams/encoder-decoder-inference",
    slug: "encoder-decoder-diagrams/encoder-decoder-inference",
  },
  // Section 10: Modern LLM Techniques
  {
    id: "14.1",
    title: "KV Cache - Why Inference is Fast",
    section: 14,
    component: "KVCache",
    file: "attention-computation/kv-cache",
    slug: "attention-computation/kv-cache",
  },
  {
    id: "14.2",
    title: "Grouped-Query Attention - Shrinking the KV Cache",
    section: 14,
    component: "GroupedQueryAttention",
    file: "attention-computation/grouped-query-attention",
    slug: "attention-computation/grouped-query-attention",
  },
  {
    id: "14.3",
    title: "Mixture of Experts - Bigger Model, Same Compute",
    section: 14,
    component: "MixtureOfExperts",
    file: "modern-llm-techniques/mixture-of-experts",
    slug: "modern-llm-techniques/mixture-of-experts",
  },
  {
    id: "14.4",
    title: "Thinking - How Reasoning Models Work",
    section: 14,
    component: "Thinking",
    file: "modern-llm-techniques/thinking",
    slug: "modern-llm-techniques/thinking",
  },
  // Section 11: Vector Databases
  {
    id: "15.1",
    title: "The Retrieval Problem",
    section: 15,
    component: "RetrievalProblem",
    file: "vector-foundations/retrieval-problem",
    slug: "vector-foundations/retrieval-problem",
  },
  {
    id: "15.2",
    title: "Brute-Force kNN",
    section: 15,
    component: "BruteForceKNN",
    file: "vector-foundations/brute-force-knn",
    slug: "vector-foundations/brute-force-knn",
  },
  {
    id: "15.3",
    title: "The Three-Way Tradeoff",
    section: 15,
    component: "ThreeWayTradeoff",
    file: "vector-foundations/three-way-tradeoff",
    slug: "vector-foundations/three-way-tradeoff",
  },
  {
    id: "15.4",
    title: "Distance Metrics",
    section: 15,
    component: "DistanceMetrics",
    file: "vector-foundations/distance-metrics",
    slug: "vector-foundations/distance-metrics",
  },
  {
    id: "15.5",
    title: "Sparse vs Dense Vectors",
    section: 15,
    component: "SparseVsDense",
    file: "vector-foundations/sparse-vs-dense",
    slug: "vector-foundations/sparse-vs-dense",
  },
  {
    id: "15.6",
    title: "The ANN Family Tree",
    section: 15,
    component: "ANNFamilyTree",
    file: "vector-foundations/ann-family-tree",
    slug: "vector-foundations/ann-family-tree",
  },
  { id: "15.7", title: "IVF (Inverted File Index)", section: 15, component: "IVF", file: "vector-foundations/ivf", slug: "vector-foundations/ivf" },
  {
    id: "15.8",
    title: "HNSW - The Small-World Intuition",
    section: 15,
    component: "HNSWIntuition",
    file: "vector-foundations/hnsw-intuition",
    slug: "vector-foundations/hnsw-intuition",
  },
  {
    id: "15.9",
    title: "HNSW Construction",
    section: 15,
    component: "HNSWConstruction",
    file: "vector-foundations/hnsw-construction",
    slug: "vector-foundations/hnsw-construction",
  },
  { id: "15.10", title: "HNSW Search", section: 15, component: "HNSWSearch", file: "vector-foundations/hnsw-search", slug: "vector-foundations/hnsw-search" },
  {
    id: "15.11",
    title: "HNSW Parameters",
    section: 15,
    component: "HNSWParameters",
    file: "vector-foundations/hnsw-parameters",
    slug: "vector-foundations/hnsw-parameters",
  },
  { id: "15.12", title: "Vamana / DiskANN", section: 15, component: "Vamana", file: "vector-foundations/vamana", slug: "vector-foundations/vamana" },
  {
    id: "16.1",
    title: "The Memory Wall",
    section: 16,
    component: "MemoryWall",
    file: "vector-compression/memory-wall",
    slug: "vector-compression/memory-wall",
  },
  {
    id: "16.2",
    title: "Scalar Quantization",
    section: 16,
    component: "ScalarQuantization",
    file: "vector-compression/scalar-quantization",
    slug: "vector-compression/scalar-quantization",
  },
  {
    id: "16.3",
    title: "Product Quantization (+ OPQ)",
    section: 16,
    component: "ProductQuantization",
    file: "vector-compression/product-quantization",
    slug: "vector-compression/product-quantization",
  },
  {
    id: "16.4",
    title: "Binary Quantization",
    section: 16,
    component: "BinaryQuantization",
    file: "vector-compression/binary-quantization",
    slug: "vector-compression/binary-quantization",
  },
  {
    id: "16.5",
    title: "Matryoshka Embeddings",
    section: 16,
    component: "Matryoshka",
    file: "vector-compression/matryoshka",
    slug: "vector-compression/matryoshka",
  },
  { id: "16.6", title: "IVF-PQ", section: 16, component: "IVFPQ", file: "vector-compression/ivf-pq", slug: "vector-compression/ivf-pq" },
  { id: "16.7", title: "HNSW + PQ", section: 16, component: "HNSWPQ", file: "vector-compression/hnsw-pq", slug: "vector-compression/hnsw-pq" },
  {
    id: "16.8",
    title: "The Compression Decision",
    section: 16,
    component: "CompressionDecision",
    file: "vector-compression/compression-decision",
    slug: "vector-compression/compression-decision",
  },
  { id: "17.1", title: "Filtering", section: 17, component: "Filtering", file: "vector-production/filtering", slug: "vector-production/filtering" },
  {
    id: "17.2",
    title: "Updates & Deletes",
    section: 17,
    component: "UpdatesDeletes",
    file: "vector-production/updates-deletes",
    slug: "vector-production/updates-deletes",
  },
  {
    id: "17.3",
    title: "Sharding & Partitioning",
    section: 17,
    component: "Sharding",
    file: "vector-production/sharding",
    slug: "vector-production/sharding",
  },
  {
    id: "17.4",
    title: "Replication & High Availability",
    section: 17,
    component: "Replication",
    file: "vector-production/replication",
    slug: "vector-production/replication",
  },
  {
    id: "17.5",
    title: "Hybrid Search",
    section: 17,
    component: "HybridSearch",
    file: "vector-production/hybrid-search",
    slug: "vector-production/hybrid-search",
  },
  { id: "17.6", title: "Rerankers", section: 17, component: "Rerankers", file: "vector-production/rerankers", slug: "vector-production/rerankers" },
  {
    id: "17.7",
    title: "Multi-vector Retrieval (ColBERT-style)",
    section: 17,
    component: "MultiVectorRetrieval",
    file: "vector-production/multi-vector-retrieval",
    slug: "vector-production/multi-vector-retrieval",
  },
  {
    id: "17.8",
    title: "Embedding Lifecycle & Re-embedding",
    section: 17,
    component: "EmbeddingLifecycle",
    file: "vector-production/embedding-lifecycle",
    slug: "vector-production/embedding-lifecycle",
  },
  {
    id: "17.9",
    title: "Observability",
    section: 17,
    component: "Observability",
    file: "vector-production/observability",
    slug: "vector-production/observability",
  },
  {
    id: "17.10",
    title: "Capacity Planning & Cost Models",
    section: 17,
    component: "CapacityPlanning",
    file: "vector-production/capacity-planning",
    slug: "vector-production/capacity-planning",
  },
  { id: "18.1", title: "FAISS", section: 18, component: "FAISS", file: "vector-systems/faiss", slug: "vector-systems/faiss" },
  { id: "18.2", title: "pgvector", section: 18, component: "Pgvector", file: "vector-systems/pgvector", slug: "vector-systems/pgvector" },
  { id: "18.3", title: "Qdrant", section: 18, component: "Qdrant", file: "vector-systems/qdrant", slug: "vector-systems/qdrant" },
  { id: "18.4", title: "Pinecone", section: 18, component: "Pinecone", file: "vector-systems/pinecone", slug: "vector-systems/pinecone" },
  {
    id: "18.5",
    title: "Qdrant vs Pinecone",
    section: 18,
    component: "QdrantVsPinecone",
    file: "vector-systems/qdrant-vs-pinecone",
    slug: "vector-systems/qdrant-vs-pinecone",
  },
  {
    id: "18.6",
    title: "Weaviate / Milvus / Chroma",
    section: 18,
    component: "WeaviateMilvusChroma",
    file: "vector-systems/weaviate-milvus-chroma",
    slug: "vector-systems/weaviate-milvus-chroma",
  },
  {
    id: "18.7",
    title: "The Decision Framework",
    section: 18,
    component: "DecisionFramework",
    file: "vector-systems/decision-framework",
    slug: "vector-systems/decision-framework",
  },
  // Section 12: Retrieval-Augmented Generation
  {
    id: "19.1",
    title: "Why LLMs Need Retrieval",
    section: 19,
    component: "WhyLLMsNeedRetrieval",
    file: "rag-foundations/why-llms-need-retrieval",
    slug: "rag-foundations/why-llms-need-retrieval",
  },
  {
    id: "19.2",
    title: "The Naive RAG Pipeline",
    section: 19,
    component: "NaiveRAGPipeline",
    file: "rag-foundations/naive-rag-pipeline",
    slug: "rag-foundations/naive-rag-pipeline",
  },
  {
    id: "19.3",
    title: "Where Naive RAG Breaks",
    section: 19,
    component: "WhereNaiveRAGBreaks",
    file: "rag-foundations/where-naive-rag-breaks",
    slug: "rag-foundations/where-naive-rag-breaks",
  },
  {
    id: "20.1",
    title: "Parsing - Raw Sources to Clean Text",
    section: 20,
    component: "ParsingExtraction",
    file: "rag-ingestion/parsing-extraction",
    slug: "rag-ingestion/parsing-extraction",
  },
  {
    id: "20.2",
    title: "Deduplication & Cleaning",
    section: 20,
    component: "DeduplicationCleaning",
    file: "rag-ingestion/deduplication-cleaning",
    slug: "rag-ingestion/deduplication-cleaning",
  },
  {
    id: "20.3",
    title: "Refresh & Sync Schedules",
    section: 20,
    component: "RefreshSync",
    file: "rag-ingestion/refresh-sync",
    slug: "rag-ingestion/refresh-sync",
  },
  {
    id: "20.4",
    title: "Why Chunk At All + Fixed-Size Baseline",
    section: 20,
    component: "WhyChunkFixedSize",
    file: "rag-foundations/why-chunk-fixed-size",
    slug: "rag-foundations/why-chunk-fixed-size",
  },
  {
    id: "20.5",
    title: "Recursive Structural Chunking",
    section: 20,
    component: "RecursiveStructuralChunking",
    file: "rag-foundations/recursive-structural-chunking",
    slug: "rag-foundations/recursive-structural-chunking",
  },
  {
    id: "20.6",
    title: "Semantic Chunking",
    section: 20,
    component: "SemanticChunking",
    file: "rag-foundations/semantic-chunking",
    slug: "rag-foundations/semantic-chunking",
  },
  {
    id: "20.7",
    title: "Late Chunking (Jina 2024)",
    section: 20,
    component: "LateChunking",
    file: "rag-foundations/late-chunking",
    slug: "rag-foundations/late-chunking",
  },
  {
    id: "20.8",
    title: "Hierarchical / Parent-Child Chunking",
    section: 20,
    component: "HierarchicalChunking",
    file: "rag-foundations/hierarchical-chunking",
    slug: "rag-foundations/hierarchical-chunking",
  },
  {
    id: "20.9",
    title: "Contextual Retrieval (Anthropic 2024)",
    section: 20,
    component: "ContextualRetrieval",
    file: "rag-foundations/contextual-retrieval",
    slug: "rag-foundations/contextual-retrieval",
  },
  {
    id: "20.10",
    title: "The Chunking Decision",
    section: 20,
    component: "ChunkingDecision",
    file: "rag-foundations/chunking-decision",
    slug: "rag-foundations/chunking-decision",
  },
  // Section 12 Act 4: Embed & Index Choices for RAG
  {
    id: "21.1",
    title: "Picking an Embedding Model",
    section: 21,
    component: "EmbeddingModelChoice",
    file: "rag-retrieval/embedding-model-choice",
    slug: "rag-retrieval/embedding-model-choice",
  },
  {
    id: "21.2",
    title: "Domain Adaptation - Fine-Tuning Embeddings",
    section: 21,
    component: "DomainAdaptation",
    file: "rag-retrieval/domain-adaptation",
    slug: "rag-retrieval/domain-adaptation",
  },
  {
    id: "21.3",
    title: "Hybrid Retrieval for RAG",
    section: 21,
    component: "HybridForRAG",
    file: "rag-retrieval/hybrid-for-rag",
    slug: "rag-retrieval/hybrid-for-rag",
  },
  {
    id: "21.4",
    title: "The Reranker Cascade",
    section: 21,
    component: "RerankerCascade",
    file: "rag-retrieval/reranker-cascade",
    slug: "rag-retrieval/reranker-cascade",
  },
  // Section 12 Act 5: Query Transformation
  {
    id: "21.5",
    title: "Why Transform Queries",
    section: 21,
    component: "WhyTransformQueries",
    file: "rag-retrieval/why-transform-queries",
    slug: "rag-retrieval/why-transform-queries",
  },
  {
    id: "21.6",
    title: "HyDE - Hypothetical Document Embeddings",
    section: 21,
    component: "HyDE",
    file: "rag-retrieval/hy-de",
    slug: "rag-retrieval/hy-de",
  },
  {
    id: "21.7",
    title: "Multi-Query Expansion",
    section: 21,
    component: "MultiQueryExpansion",
    file: "rag-retrieval/multi-query-expansion",
    slug: "rag-retrieval/multi-query-expansion",
  },
  {
    id: "21.8",
    title: "Query Routing & Decomposition",
    section: 21,
    component: "QueryRoutingDecomposition",
    file: "rag-retrieval/query-routing-decomposition",
    slug: "rag-retrieval/query-routing-decomposition",
  },
  // Section 12 Acts 6+7: Context & Generation, Advanced Retrieval Patterns
  {
    id: "22.1",
    title: "Context Packing",
    section: 22,
    component: "ContextPacking",
    file: "rag-generation/context-packing",
    slug: "rag-generation/context-packing",
  },
  {
    id: "22.2",
    title: "The Lost-in-the-Middle Problem",
    section: 22,
    component: "LostInTheMiddle",
    file: "rag-generation/lost-in-the-middle",
    slug: "rag-generation/lost-in-the-middle",
  },
  {
    id: "22.3",
    title: "Citations, Refusal & Groundedness",
    section: 22,
    component: "CitationsRefusal",
    file: "rag-generation/citations-refusal",
    slug: "rag-generation/citations-refusal",
  },
  {
    id: "22.4",
    title: "Multi-Hop Retrieval",
    section: 22,
    component: "MultiHopRetrieval",
    file: "rag-generation/multi-hop-retrieval",
    slug: "rag-generation/multi-hop-retrieval",
  },
  { id: "22.5", title: "Self-RAG", section: 22, component: "SelfRAG", file: "rag-generation/self-rag", slug: "rag-generation/self-rag" },
  {
    id: "22.6",
    title: "CRAG - Corrective RAG",
    section: 22,
    component: "CorrectiveRAG",
    file: "rag-generation/corrective-rag",
    slug: "rag-generation/corrective-rag",
  },
  {
    id: "22.7",
    title: "GraphRAG (Microsoft 2024)",
    section: 22,
    component: "GraphRAG",
    file: "rag-generation/graph-rag",
    slug: "rag-generation/graph-rag",
  },
  {
    id: "22.8",
    title: "Tool-Augmented & Agentic RAG",
    section: 22,
    component: "AgenticRAG",
    file: "rag-generation/agentic-rag",
    slug: "rag-generation/agentic-rag",
  },
  {
    id: "22.9",
    title: "Long-Context vs RAG",
    section: 22,
    component: "LongContextVsRAG",
    file: "rag-generation/long-context-vs-rag",
    slug: "rag-generation/long-context-vs-rag",
  },
  // Section 12 Act 8: Evaluation
  {
    id: "23.1",
    title: "The RAG Eval Triangle",
    section: 23,
    component: "RAGEvalTriangle",
    file: "rag-evaluation/rag-eval-triangle",
    slug: "rag-evaluation/rag-eval-triangle",
  },
  { id: "23.2", title: "LLM-as-Judge", section: 23, component: "LLMAsJudge", file: "rag-evaluation/llm-as-judge", slug: "rag-evaluation/llm-as-judge" },
  { id: "23.3", title: "RAGAS Metrics", section: 23, component: "RAGASMetrics", file: "rag-evaluation/ragas-metrics", slug: "rag-evaluation/ragas-metrics" },
  {
    id: "23.4",
    title: "Golden Datasets",
    section: 23,
    component: "GoldenDatasets",
    file: "rag-evaluation/golden-datasets",
    slug: "rag-evaluation/golden-datasets",
  },
  {
    id: "23.5",
    title: "Online Eval & A/B Testing",
    section: 23,
    component: "OnlineEvalABTesting",
    file: "rag-evaluation/online-eval-ab-testing",
    slug: "rag-evaluation/online-eval-ab-testing",
  },
  // Section 12 Act 9: Production Operations
  {
    id: "23.6",
    title: "Caching - Prompt + Semantic",
    section: 23,
    component: "Caching",
    file: "rag-production/caching",
    slug: "rag-production/caching",
  },
  { id: "23.7", title: "Cost Models", section: 23, component: "CostModels", file: "rag-production/cost-models", slug: "rag-production/cost-models" },
  {
    id: "23.8",
    title: "Observability & Tracing",
    section: 23,
    component: "ObservabilityTracing",
    file: "rag-production/observability-tracing",
    slug: "rag-production/observability-tracing",
  },
  {
    id: "23.9",
    title: "Hallucination Detection & Drift",
    section: 23,
    component: "HallucinationDrift",
    file: "rag-production/hallucination-drift",
    slug: "rag-production/hallucination-drift",
  },
  {
    id: "23.10",
    title: "Framework Choice",
    section: 23,
    component: "FrameworkChoice",
    file: "rag-production/framework-choice",
    slug: "rag-production/framework-choice",
  },
  // Section 12 Act 10: Decision Framework + Capstone
  {
    id: "23.11",
    title: "The Complete RAG Decision Framework + Capstone",
    section: 23,
    component: "RAGDecisionFrameworkCapstone",
    file: "rag-production/rag-decision-framework-capstone",
    slug: "rag-production/rag-decision-framework-capstone",
  },
  // Section 13: AI Agents
  {
    id: "24.1",
    title: "Anatomy of an LLM Call",
    section: 24,
    component: "AnatomyOfLlmCall",
    file: "agent-prompting/anatomy-of-llm-call",
    slug: "agent-prompting/anatomy-of-llm-call",
  },
  {
    id: "24.2",
    title: "System Prompts - The Role Contract",
    section: 24,
    component: "SystemPromptContract",
    file: "agent-prompting/system-prompt-contract",
    slug: "agent-prompting/system-prompt-contract",
  },
  {
    id: "24.3",
    title: "Few-Shot + Structured Output",
    section: 24,
    component: "FewShotStructuredOutput",
    file: "agent-prompting/few-shot-structured-output",
    slug: "agent-prompting/few-shot-structured-output",
  },
  {
    id: "24.4",
    title: "Chain of Thought + Self-Consistency",
    section: 24,
    component: "ChainOfThoughtSelfConsistency",
    file: "agent-prompting/chain-of-thought-self-consistency",
    slug: "agent-prompting/chain-of-thought-self-consistency",
  },
  {
    id: "24.5",
    title: "Prompt vs Fine-Tune vs RAG vs Agent",
    section: 24,
    component: "PromptVsTuneVsRagVsAgent",
    file: "agent-prompting/prompt-vs-tune-vs-rag-vs-agent",
    slug: "agent-prompting/prompt-vs-tune-vs-rag-vs-agent",
  },
  {
    id: "24.6",
    title: "Context Engineering",
    section: 24,
    component: "ContextEngineering",
    file: "agent-prompting/context-engineering",
    slug: "agent-prompting/context-engineering",
  },
  {
    id: "25.1",
    title: "Tool Use - LLM as Orchestrator",
    section: 25,
    component: "ToolUseAsBridge",
    file: "agent-tools/tool-use-as-bridge",
    slug: "agent-tools/tool-use-as-bridge",
  },
  {
    id: "25.2",
    title: "JSON Schemas + Tool Descriptions",
    section: 25,
    component: "JsonSchemaForTools",
    file: "agent-tools/json-schema-for-tools",
    slug: "agent-tools/json-schema-for-tools",
  },
  {
    id: "25.3",
    title: "Tool Call Lifecycle",
    section: 25,
    component: "ToolCallLifecycle",
    file: "agent-tools/tool-call-lifecycle",
    slug: "agent-tools/tool-call-lifecycle",
  },
  {
    id: "25.4",
    title: "Parallel Tools + Tool Choice",
    section: 25,
    component: "ParallelToolsAndChoice",
    file: "agent-tools/parallel-tools-and-choice",
    slug: "agent-tools/parallel-tools-and-choice",
  },
  {
    id: "25.5",
    title: "Tool Errors, Retries, Validation",
    section: 25,
    component: "ToolErrorsRetries",
    file: "agent-tools/tool-errors-retries",
    slug: "agent-tools/tool-errors-retries",
  },
  { id: "25.6", title: "Why Protocols?", section: 25, component: "WhyProtocols", file: "agent-tools/why-protocols", slug: "agent-tools/why-protocols" },
  {
    id: "25.7",
    title: "MCP Architecture",
    section: 25,
    component: "McpArchitecture",
    file: "agent-tools/mcp-architecture",
    slug: "agent-tools/mcp-architecture",
  },
  {
    id: "25.8",
    title: "MCP Primitives - Tools, Resources, Prompts",
    section: 25,
    component: "McpPrimitives",
    file: "agent-tools/mcp-primitives",
    slug: "agent-tools/mcp-primitives",
  },
  {
    id: "25.9",
    title: "Building an MCP Server",
    section: 25,
    component: "BuildingMcpServer",
    file: "agent-tools/building-mcp-server",
    slug: "agent-tools/building-mcp-server",
  },
  { id: "25.10", title: "MCP Security", section: 25, component: "McpSecurity", file: "agent-tools/mcp-security", slug: "agent-tools/mcp-security" },
  {
    id: "25.11",
    title: "A2A - Agent-to-Agent Protocol",
    section: 25,
    component: "A2AProtocol",
    file: "agent-tools/a2a-protocol",
    slug: "agent-tools/a2a-protocol",
  },
  {
    id: "26.1",
    title: "Workflow vs Agent",
    section: 26,
    component: "WorkflowVsAgent",
    file: "agent-loops/workflow-vs-agent",
    slug: "agent-loops/workflow-vs-agent",
  },
  {
    id: "26.2",
    title: "Workflow Primitives - Chaining, Routing, Parallelization",
    section: 26,
    component: "WorkflowPrimitives",
    file: "agent-loops/workflow-primitives",
    slug: "agent-loops/workflow-primitives",
  },
  { id: "26.3", title: "The Agent Loop", section: 26, component: "AgentLoop", file: "agent-loops/agent-loop", slug: "agent-loops/agent-loop" },
  { id: "26.4", title: "ReAct Pattern", section: 26, component: "ReActPattern", file: "agent-loops/re-act-pattern", slug: "agent-loops/re-act-pattern" },
  {
    id: "26.5",
    title: "Plan-Execute + Reflection",
    section: 26,
    component: "PlanExecuteReflect",
    file: "agent-loops/plan-execute-reflect",
    slug: "agent-loops/plan-execute-reflect",
  },
  {
    id: "26.6",
    title: "Loop Termination",
    section: 26,
    component: "LoopTermination",
    file: "agent-loops/loop-termination",
    slug: "agent-loops/loop-termination",
  },
  {
    id: "26.7",
    title: "Memory Taxonomy - Short vs Long",
    section: 26,
    component: "MemoryTaxonomy",
    file: "agent-loops/memory-taxonomy",
    slug: "agent-loops/memory-taxonomy",
  },
  {
    id: "26.8",
    title: "Working Memory - The Scratchpad",
    section: 26,
    component: "WorkingMemory",
    file: "agent-loops/working-memory",
    slug: "agent-loops/working-memory",
  },
  {
    id: "26.9",
    title: "Episodic Memory - Past Events",
    section: 26,
    component: "EpisodicMemory",
    file: "agent-loops/episodic-memory",
    slug: "agent-loops/episodic-memory",
  },
  {
    id: "26.10",
    title: "Semantic Memory - Learned Facts",
    section: 26,
    component: "SemanticMemory",
    file: "agent-loops/semantic-memory",
    slug: "agent-loops/semantic-memory",
  },
  {
    id: "26.11",
    title: "Procedural Memory - Learned Skills",
    section: 26,
    component: "ProceduralMemory",
    file: "agent-loops/procedural-memory",
    slug: "agent-loops/procedural-memory",
  },
  {
    id: "26.12",
    title: "Summary Memory + Context Window Management",
    section: 26,
    component: "SummaryAndContextMgmt",
    file: "agent-loops/summary-and-context-mgmt",
    slug: "agent-loops/summary-and-context-mgmt",
  },
  {
    id: "27.1",
    title: "Why Multi-Agent?",
    section: 27,
    component: "WhyMultiAgent",
    file: "multi-agent/why-multi-agent",
    slug: "multi-agent/why-multi-agent",
  },
  {
    id: "27.2",
    title: "Orchestrator-Worker",
    section: 27,
    component: "OrchestratorWorker",
    file: "multi-agent/orchestrator-worker",
    slug: "multi-agent/orchestrator-worker",
  },
  {
    id: "27.3",
    title: "Supervisor / Hierarchical",
    section: 27,
    component: "SupervisorHierarchy",
    file: "multi-agent/supervisor-hierarchy",
    slug: "multi-agent/supervisor-hierarchy",
  },
  { id: "27.4", title: "Hand-Offs", section: 27, component: "AgentHandoffs", file: "multi-agent/agent-handoffs", slug: "multi-agent/agent-handoffs" },
  {
    id: "27.5",
    title: "Critic / Debate / Reflection-as-Multi-Agent",
    section: 27,
    component: "CriticDebate",
    file: "multi-agent/critic-debate",
    slug: "multi-agent/critic-debate",
  },
  {
    id: "27.6",
    title: "Multi-Agent Failure Modes",
    section: 27,
    component: "MultiAgentFailures",
    file: "multi-agent/multi-agent-failures",
    slug: "multi-agent/multi-agent-failures",
  },
  { id: "27.7", title: "Agentic RAG", section: 27, component: "AgenticRag", file: "multi-agent/agentic-rag", slug: "multi-agent/agentic-rag" },
  {
    id: "28.1",
    title: "Why Eval Agents Differently",
    section: 28,
    component: "WhyEvalAgents",
    file: "agent-evals/why-eval-agents",
    slug: "agent-evals/why-eval-agents",
  },
  {
    id: "28.2",
    title: "Eval Dimensions",
    section: 28,
    component: "EvalDimensions",
    file: "agent-evals/eval-dimensions",
    slug: "agent-evals/eval-dimensions",
  },
  { id: "28.3", title: "LLM-as-Judge", section: 28, component: "LlmAsJudge", file: "agent-evals/llm-as-judge", slug: "agent-evals/llm-as-judge" },
  { id: "28.4", title: "Trace Evals", section: 28, component: "TraceEvals", file: "agent-evals/trace-evals", slug: "agent-evals/trace-evals" },
  {
    id: "28.5",
    title: "Eval Sets + Continuous Eval",
    section: 28,
    component: "EvalSetsContinuous",
    file: "agent-evals/eval-sets-continuous",
    slug: "agent-evals/eval-sets-continuous",
  },
  {
    id: "28.6",
    title: "Observability & Tracing",
    section: 28,
    component: "AgentObservabilityTracing",
    file: "agent-production/agent-observability-tracing",
    slug: "agent-production/agent-observability-tracing",
  },
  { id: "28.7", title: "Cost Control", section: 28, component: "CostControl", file: "agent-production/cost-control", slug: "agent-production/cost-control" },
  {
    id: "28.8",
    title: "Latency Optimization",
    section: 28,
    component: "LatencyOptimization",
    file: "agent-production/latency-optimization",
    slug: "agent-production/latency-optimization",
  },
  { id: "28.9", title: "Guardrails", section: 28, component: "Guardrails", file: "agent-production/guardrails", slug: "agent-production/guardrails" },
  {
    id: "28.10",
    title: "Prompt Injection Defenses",
    section: 28,
    component: "PromptInjectionDefenses",
    file: "agent-production/prompt-injection-defenses",
    slug: "agent-production/prompt-injection-defenses",
  },
  {
    id: "28.11",
    title: "Tool Security",
    section: 28,
    component: "ToolSecurity",
    file: "agent-production/tool-security",
    slug: "agent-production/tool-security",
  },
  {
    id: "28.12",
    title: "LangGraph",
    section: 28,
    component: "LangGraphFramework",
    file: "agent-production/lang-graph-framework",
    slug: "agent-production/lang-graph-framework",
  },
  {
    id: "28.13",
    title: "CrewAI / AutoGen",
    section: 28,
    component: "CrewAiAutoGen",
    file: "agent-production/crew-ai-auto-gen",
    slug: "agent-production/crew-ai-auto-gen",
  },
  {
    id: "28.14",
    title: "Claude Agent SDK + OpenAI Agents",
    section: 28,
    component: "VendorSdks",
    file: "agent-production/vendor-sdks",
    slug: "agent-production/vendor-sdks",
  },
  {
    id: "28.15",
    title: "Custom / No-Framework",
    section: 28,
    component: "CustomNoFramework",
    file: "agent-production/custom-no-framework",
    slug: "agent-production/custom-no-framework",
  },
  {
    id: "28.16",
    title: "The Complete Agent Decision Framework",
    section: 28,
    component: "AgentDecisionFramework",
    file: "agent-production/agent-decision-framework",
    slug: "agent-production/agent-decision-framework",
  },
];

export const sectionNames = {
  0: "Overview",
  1: "Neural Networks - The Mechanics",
  2: "Learning & Backprop",
  3: "Linear Algebra for Deep Learning",
  4: "Training Deep Networks",
  5: "How LLMs Actually Train",
  6: "Scaling & Modern Techniques",
  7: "The Road to Transformers",
  8: "Transformer Input Pipeline",
  9: "Attention - Understanding Q, K, V",
  10: "Computing Attention",
  11: "Multi-Head Attention",
  12: "The Encoder",
  13: "The Decoder",
  14: "Modern LLM Techniques",
  15: "Vector Search - From Brute Force to ANN",
  16: "Vector Compression - Quantization & Matryoshka",
  17: "Vector DBs in Production",
  18: "Picking a Vector Database",
  19: "The RAG Pipeline - Why & How It Breaks",
  20: "RAG Data Prep - Ingestion & Chunking",
  21: "RAG Retrieval - Embeddings, Hybrid & Query Tricks",
  22: "RAG Generation - Naive to Advanced Patterns",
  23: "RAG in Production - Eval, Cost & Shipping",
  24: "Prompting LLMs - The Foundation",
  25: "Tools & Protocols - MCP, A2A",
  26: "Agent Mechanics - Loops & Memory",
  27: "Multi-Agent Systems",
  28: "Shipping Agents - Eval, Safety, Frameworks",
};

// Section colors (one per section, used in progress bar, TOC, etc.)
export const sectionColors = {
  1: "#ff6b6b",
  2: "#ff8a80",
  3: "#ef9a9a",
  4: "#e57373",
  5: "#00b8d4",
  6: "#ffd740",
  7: "#a78bfa",
  8: "#ffab40",
  9: "#00e676",
  10: "#e040fb",
  11: "#ce93d8",
  12: "#42a5f5",
  13: "#ef5350",
  14: "#26a69a",
  15: "#f06292",
  16: "#ec407a",
  17: "#d81b60",
  18: "#ad1457",
  19: "#9ccc65",
  20: "#66bb6a",
  21: "#4db6ac",
  22: "#00897b",
  23: "#2e7d32",
  24: "#4fc3f7",
  25: "#1976d2",
  26: "#5c6bc0",
  27: "#7e57c2",
  28: "#5e35b3",
};

// Colors
export const C = {
  bg: "#08080d",
  card: "rgba(255,255,255,0.025)",
  border: "rgba(255,255,255,0.07)",
  dim: "rgba(255,255,255,0.35)",
  mid: "rgba(255,255,255,0.55)",
  bright: "rgba(255,255,255,0.85)",
  red: "#ff6b6b",
  purple: "#a78bfa",
  green: "#00e676",
  cyan: "#00b8d4",
  yellow: "#ffd740",
  pink: "#e040fb",
  orange: "#ffab40",
  blue: "#42a5f5",
  indigo: "#5c6bc0",
  teal: "#26c6da",
  amber: "#ffc107",
};

export const superSections = [
  { id: "A", name: "Foundations of Deep Learning",         color: "#ff6b6b", sections: [1, 2, 3, 4] },
  { id: "B", name: "The Rise of LLMs",                     color: "#00b8d4", sections: [5, 6] },
  { id: "C", name: "The Transformer Era",                  color: "#a78bfa", sections: [7, 8, 9, 10, 11, 12, 13, 14] },
  { id: "D", name: "Vector Databases at Depth",            color: "#f06292", sections: [15, 16, 17, 18] },
  { id: "E", name: "Retrieval-Augmented Generation (RAG)", color: "#9ccc65", sections: [19, 20, 21, 22, 23] },
  { id: "F", name: "Agentic AI",                           color: "#4fc3f7", sections: [24, 25, 26, 27, 28] },
];

// Validate config - extracted for testability
export function validateConfig(chapterList) {
  const errors = [];
  const ids = chapterList.map((c) => c.id);
  const dupes = ids.filter((id, i) => ids.indexOf(id) !== i);
  if (dupes.length) errors.push(`Duplicate chapter IDs: ${dupes.join(", ")}`);
  chapterList.forEach((c) => {
    if (c.component && !c.id) errors.push(`Chapter missing id: ${c.component}`);
    if (!c.component) errors.push(`Chapter missing component: id=${c.id}`);
  });
  return errors;
}

// Config validation runs via tests (see config.test.js) using validateConfig().
