export const chapters = [
  { id: "0", title: "Table of Contents", section: 0, component: "TOC" },
  // Section 1: Neural Network Foundations
  { id: "1.1", title: "What is a Neural Network?", section: 1, component: "WhatIsNN" },
  { id: "1.2", title: "Inside a Single Neuron", section: 1, component: "InsideNeuron" },
  { id: "1.3", title: "What is a Layer?", section: 1, component: "WhatIsLayer" },
  { id: "1.4", title: "Weights & Biases - The Knobs", section: 1, component: "WeightsBiases" },
  { id: "1.5", title: "Why Linear Isn't Enough", section: 1, component: "WhyLinear" },
  { id: "1.6", title: "Activation (ReLU) - Why Layers Need a Bend", section: 1, component: "ReLU" },
  { id: "1.7", title: "The Forward Pass - Full Example", section: 1, component: "ForwardPass" },
  { id: "1.8", title: "Loss - How Wrong Were We?", section: 1, component: "LossFunction" },
  { id: "1.9", title: "Learning - What Does It Mean?", section: 1, component: "WhatIsLearning" },
  { id: "1.10", title: "Derivatives - The Core Intuition", section: 1, component: "Derivatives" },
  { id: "1.11", title: "The Backward Pass - The Chain Rule", section: 1, component: "BackwardPass" },
  { id: "1.12", title: "Gradient Descent - Fixing the Weights", section: 1, component: "GradientDescent" },
  { id: "1.13", title: "Backprop Through the Real Network", section: 1, component: "BackpropRealNetwork" },
  { id: "1.14", title: "Gradients in Action - The Full Training Loop", section: 1, component: "GradientsInAction" },
  { id: "1.15", title: "Why Deep Backprop Gets Hard", section: 1, component: "WhyBackpropHard" },
  { id: "1.16", title: "Vectors - Numbers That Travel Together", section: 1, component: "Vectors" },
  { id: "1.17", title: "The Dot Product - How Vectors Compare", section: 1, component: "DotProductIntro" },
  { id: "1.18", title: "Matrices - Grids That Transform Vectors", section: 1, component: "Matrices" },
  { id: "1.19", title: "A Layer is Matrix Multiplication", section: 1, component: "LayerIsMatMul" },
  { id: "1.20", title: "Activation Functions - The Full Picture", section: 1, component: "ActivationFunctions" },
  { id: "1.21", title: 'What "Deep" Really Means', section: 1, component: "WhatDeepMeans" },
  { id: "1.22", title: "Same Building Blocks, Different Shapes", section: 1, component: "SameBuildingBlocks" },
  { id: "1.23", title: "Dropout - The Regularization Trick", section: 1, component: "Dropout" },
  { id: "1.24", title: "Adam - The Real Optimizer", section: 1, component: "AdamOptimizer" },
  { id: "1.25", title: "Learning Rate Warmup & Decay", section: 1, component: "LRWarmupDecay" },
  { id: "1.26", title: "Weight Initialization - How Random?", section: 1, component: "WeightInit" },
  // Section 2: How LLMs Actually Train (reordered: output/generation before fine-tuning)
  { id: "2.1", title: "Tokenization - From Words to Numbers", section: 2, component: "Tokenization" },
  { id: "2.2", title: "Self-Supervised Learning - How GPT Trains", section: 2, component: "SelfSupervised" },
  { id: "2.3", title: "Cross-Entropy Loss - The LLM Score", section: 2, component: "CrossEntropy" },
  { id: "2.4", title: "The Neural Network in Action", section: 2, component: "NNInAction" },
  { id: "2.5", title: "The Output Layer - From Hidden State to Words", section: 2, component: "OutputLayer" },
  {
    id: "2.6",
    title: "Autoregressive Generation - One Token at a Time",
    section: 2,
    component: "AutoregressiveGeneration",
  },
  { id: "2.7", title: "Supervised Fine-Tuning (SFT)", section: 2, component: "SFT" },
  { id: "2.8", title: "RLHF - Making AI Helpful & Safe", section: 2, component: "RLHF" },
  { id: "2.9", title: "DPO - Simpler Alignment", section: 2, component: "DPO" },
  {
    id: "2.10",
    title: "Tokenizer Deep Dive - BPE, WordPiece, SentencePiece",
    section: 2,
    component: "TokenizerDeepDive",
  },
  // Section 3: Scaling & Modern Techniques (BatchTraining added)
  { id: "3.1", title: "Scaling Laws - Why Bigger Models Win", section: 3, component: "ScalingLaws" },
  { id: "3.2", title: "Parameters at Scale", section: 3, component: "ParametersAtScale" },
  { id: "3.3", title: "Batch Training - Why Not One Example at a Time?", section: 3, component: "BatchTraining" },
  { id: "3.4", title: "Knowledge Distillation - Teacher to Student", section: 3, component: "Distillation" },
  { id: "3.5", title: "CLIP - Teaching AI to See & Read", section: 3, component: "CLIP" },
  { id: "3.6", title: "The Complete Training Pipeline", section: 3, component: "TrainingPipeline" },
  // Section 4: The Road to Transformers (trimmed: encoder/decoder moved to Sections 8-9)
  { id: "4.1", title: "CNN", section: 4, component: "CNN" },
  { id: "4.2", title: "RNN", section: 4, component: "RNN" },
  { id: "4.3", title: "RNN's Fatal Flaws", section: 4, component: "RNNFlaws" },
  { id: "4.4", title: "The Transformer Arrives", section: 4, component: "TransformerArrives" },
  // Section 5: Transformer Input Pipeline (trimmed: WhatTransformerDoes moved to Section 9)
  { id: "5.1", title: "The Full Architecture", section: 5, component: "FullArchitecture" },
  { id: "5.2", title: "Zoom: Embeddings", section: 5, component: "Embeddings" },
  { id: "5.3", title: "Positional Encoding - The Problem", section: 5, component: "PosEncodingProblem" },
  { id: "5.4", title: "Positional Encoding - The Formula", section: 5, component: "PosEncodingFormula" },
  { id: "5.5", title: "Positional Encoding - Computing Positions", section: 5, component: "PosEncodingCompute" },
  { id: "5.6", title: "Positional Encoding - Fast vs Slow", section: 5, component: "PosEncodingFastSlow" },
  { id: "5.7", title: "Positional Encoding - Final Addition", section: 5, component: "PosEncodingFinal" },
  { id: "5.8", title: "Positional Encoding - The Heatmap", section: 5, component: "PosEncodingHeatmap" },
  { id: "5.9", title: "RoPE - Rotary Position Embeddings", section: 5, component: "RoPE" },
  // Section 6: Attention - Understanding Q, K, V
  { id: "6.1", title: "The Problem - Context is Everything", section: 6, component: "ContextProblem" },
  { id: "6.2", title: "How Does a Word Look At Others?", section: 6, component: "WordLookup" },
  { id: "6.3", title: "The Dot Product - Measuring Similarity", section: 6, component: "DotProduct" },
  { id: "6.4", title: "Why Not Dot Product Embeddings Directly?", section: 6, component: "WhyNotDirectDot" },
  { id: "6.5", title: "Q, K, V - The Classroom Analogy", section: 6, component: "QKVClassroom" },
  { id: "6.6", title: "Every Word is Both Asker and Answerer", section: 6, component: "AskerAnswerer" },
  { id: "6.7", title: "Why Can\'t Key and Value Be the Same?", section: 6, component: "WhyKVDifferent" },
  { id: "6.8", title: "The Google Search Analogy", section: 6, component: "GoogleAnalogy" },
  { id: "6.9", title: "How Are Q, K, V Created?", section: 6, component: "HowQKVCreated" },
  { id: "6.10", title: "Shapes - Why Q is Smaller Than the Embedding", section: 6, component: "QKVShapes" },
  { id: "6.11", title: "W Matrices - Learned During Training", section: 6, component: "WMatrices" },
  { id: "6.12", title: "Tracing a Complete Example", section: 6, component: "TracingExample" },
  // Section 7: Attention - The Full Computation (CausalMask/CrossAttention moved to Section 9)
  { id: "7.1", title: "Step 1 - Compute Q, K, V for Every Word", section: 7, component: "ComputeQKV" },
  { id: "7.2", title: "Step 2 - Attention Scores (Dot Products)", section: 7, component: "AttentionScores" },
  { id: "7.3", title: "Why K Transpose? - Making the Shapes Fit", section: 7, component: "KTranspose" },
  { id: "7.4", title: "Why Do We Need Softmax?", section: 7, component: "WhySoftmax" },
  { id: "7.5", title: "Step 3 - Scale by \u221Ad_k", section: 7, component: "ScaleByRootDk" },
  { id: "7.6", title: "Step 4 - Softmax \u2192 Probabilities", section: 7, component: "SoftmaxProbs" },
  { id: "7.7", title: "Step 5 - Weighted Sum of Values", section: 7, component: "WeightedSum" },
  { id: "7.8", title: "The Full Formula", section: 7, component: "FullFormula" },
  { id: "7.9", title: "Why Multi-Head? - The Compromise Problem", section: 7, component: "WhyMultiHead" },
  { id: "7.10", title: "The Split - How 8 Heads Work", section: 7, component: "HeadSplit" },
  { id: "7.11", title: "Inside Each Head - Full Attention in 64 Dims", section: 7, component: "InsideEachHead" },
  { id: "7.12", title: "Concat + W_O - Blending All Heads", section: 7, component: "ConcatWO" },
  { id: "7.13", title: "Why 8 Heads? Parameter Count & Big Picture", section: 7, component: "WhyEightHeads" },
  { id: "7.14", title: "Is W_O Constant? Does It Change?", section: 7, component: "IsWOConstant" },
  { id: "7.15", title: "Attention Flow - Shapes at Every Step", section: 7, component: "AttentionShapes" },
  { id: "7.16", title: "The Complete Picture - In Plain English", section: 7, component: "CompletePicture" },
  // Section 8: The Encoder (EncoderDecoder opens, then Add&Norm/FFN/block repeats)
  { id: "8.1", title: "Encoder & Decoder - The Two Halves", section: 8, component: "EncoderDecoder" },
  { id: "8.2", title: "Add & Norm - The Stabilizer", section: 8, component: "AddNorm" },
  { id: "8.3", title: "FFN - The Feed-Forward Network", section: 8, component: "FeedForwardNetwork" },
  { id: "8.4", title: "FFN - Why Word Count Doesn't Matter", section: 8, component: "FFNParallelTrick" },
  { id: "8.5", title: "Add & Norm (Again) - The Second Stabilizer", section: 8, component: "AddNormTwo" },
  { id: "8.6", title: "Nx - The Transformer Block Repeats", section: 8, component: "TransformerBlockRepeats" },
  { id: "8.7", title: "Residual Connections - The Gradient Highway", section: 8, component: "ResidualHighway" },
  { id: "8.8", title: "Pre-Norm vs Post-Norm", section: 8, component: "PreNormVsPostNorm" },
  { id: "8.9", title: "Batch Norm vs Layer Norm", section: 8, component: "BatchNormVsLayerNorm" },
  // Section 9: The Decoder (decoder-only, causal masking, cross-attention, capstone)
  { id: "9.1", title: "Decoder-Only - How Modern LLMs Work", section: 9, component: "DecoderOnly" },
  { id: "9.2", title: "Causal Masking - Hiding the Future", section: 9, component: "CausalMask" },
  { id: "9.3", title: "Cross-Attention - The Encoder-Decoder Bridge", section: 9, component: "CrossAttention" },
  { id: "9.4", title: "The Output Head - Linear + Softmax", section: 9, component: "OutputHead" },
  { id: "9.5", title: "What is a Transformer Actually Doing?", section: 9, component: "WhatTransformerDoes" },
  { id: "9.6", title: "Encoder-Decoder: The Training Flow", section: 9, component: "EncoderDecoderTraining" },
  { id: "9.7", title: "Encoder-Decoder: The Inference Flow", section: 9, component: "EncoderDecoderInference" },
  // Section 10: Modern LLM Techniques
  { id: "10.1", title: "KV Cache - Why Inference is Fast", section: 10, component: "KVCache" },
  {
    id: "10.2",
    title: "Grouped-Query Attention - Shrinking the KV Cache",
    section: 10,
    component: "GroupedQueryAttention",
  },
  { id: "10.3", title: "Mixture of Experts - Bigger Model, Same Compute", section: 10, component: "MixtureOfExperts" },
  { id: "10.4", title: "Thinking - How Reasoning Models Work", section: 10, component: "Thinking" },
  // Section 11: Vector Databases
  { id: "11.1", title: "The Retrieval Problem", section: 11, component: "RetrievalProblem" },
  { id: "11.2", title: "Brute-Force kNN", section: 11, component: "BruteForceKNN" },
  { id: "11.3", title: "The Three-Way Tradeoff", section: 11, component: "ThreeWayTradeoff" },
  { id: "11.4", title: "Distance Metrics", section: 11, component: "DistanceMetrics" },
  { id: "11.5", title: "The ANN Family Tree", section: 11, component: "ANNFamilyTree" },
  { id: "11.6", title: "IVF (Inverted File Index)", section: 11, component: "IVF" },
  { id: "11.7", title: "HNSW - The Small-World Intuition", section: 11, component: "HNSWIntuition" },
  { id: "11.8", title: "HNSW Construction", section: 11, component: "HNSWConstruction" },
  { id: "11.9", title: "HNSW Search", section: 11, component: "HNSWSearch" },
  { id: "11.10", title: "HNSW Parameters", section: 11, component: "HNSWParameters" },
  { id: "11.11", title: "Vamana / DiskANN", section: 11, component: "Vamana" },
  { id: "11.12", title: "The Memory Wall", section: 11, component: "MemoryWall" },
  { id: "11.13", title: "Scalar Quantization", section: 11, component: "ScalarQuantization" },
  { id: "11.14", title: "Product Quantization (+ OPQ)", section: 11, component: "ProductQuantization" },
  { id: "11.15", title: "Binary Quantization", section: 11, component: "BinaryQuantization" },
  { id: "11.16", title: "Matryoshka Embeddings", section: 11, component: "Matryoshka" },
  { id: "11.17", title: "IVF-PQ", section: 11, component: "IVFPQ" },
  { id: "11.18", title: "HNSW + PQ", section: 11, component: "HNSWPQ" },
  { id: "11.19", title: "The Compression Decision", section: 11, component: "CompressionDecision" },
  { id: "11.20", title: "Filtering", section: 11, component: "Filtering" },
  { id: "11.21", title: "Updates & Deletes", section: 11, component: "UpdatesDeletes" },
  { id: "11.22", title: "Sharding & Partitioning", section: 11, component: "Sharding" },
  { id: "11.23", title: "Replication & High Availability", section: 11, component: "Replication" },
  { id: "11.24", title: "Hybrid Search", section: 11, component: "HybridSearch" },
  { id: "11.25", title: "Rerankers", section: 11, component: "Rerankers" },
  { id: "11.26", title: "Multi-vector Retrieval (ColBERT-style)", section: 11, component: "MultiVectorRetrieval" },
  { id: "11.27", title: "Embedding Lifecycle & Re-embedding", section: 11, component: "EmbeddingLifecycle" },
  { id: "11.28", title: "Observability", section: 11, component: "Observability" },
  { id: "11.29", title: "Capacity Planning & Cost Models", section: 11, component: "CapacityPlanning" },
  { id: "11.30", title: "FAISS", section: 11, component: "FAISS" },
  { id: "11.31", title: "pgvector", section: 11, component: "Pgvector" },
  { id: "11.32", title: "Qdrant", section: 11, component: "Qdrant" },
  { id: "11.33", title: "Pinecone", section: 11, component: "Pinecone" },
  { id: "11.34", title: "Qdrant vs Pinecone", section: 11, component: "QdrantVsPinecone" },
  { id: "11.35", title: "Weaviate / Milvus / Chroma", section: 11, component: "WeaviateMilvusChroma" },
  { id: "11.36", title: "The Decision Framework", section: 11, component: "DecisionFramework" },
  // Section 12: Retrieval-Augmented Generation
  { id: "12.1", title: "Why LLMs Need Retrieval", section: 12, component: "WhyLLMsNeedRetrieval" },
  { id: "12.2", title: "The Naive RAG Pipeline", section: 12, component: "NaiveRAGPipeline" },
  { id: "12.3", title: "Where Naive RAG Breaks", section: 12, component: "WhereNaiveRAGBreaks" },
  { id: "12.4", title: "Parsing - Raw Sources to Clean Text", section: 12, component: "ParsingExtraction" },
  { id: "12.5", title: "Deduplication & Cleaning", section: 12, component: "DeduplicationCleaning" },
  { id: "12.6", title: "Refresh & Sync Schedules", section: 12, component: "RefreshSync" },
  { id: "12.7", title: "Why Chunk At All + Fixed-Size Baseline", section: 12, component: "WhyChunkFixedSize" },
  { id: "12.8", title: "Recursive Structural Chunking", section: 12, component: "RecursiveStructuralChunking" },
  { id: "12.9", title: "Semantic Chunking", section: 12, component: "SemanticChunking" },
  { id: "12.10", title: "Late Chunking (Jina 2024)", section: 12, component: "LateChunking" },
  { id: "12.11", title: "Hierarchical / Parent-Child Chunking", section: 12, component: "HierarchicalChunking" },
  { id: "12.12", title: "Contextual Retrieval (Anthropic 2024)", section: 12, component: "ContextualRetrieval" },
  { id: "12.13", title: "The Chunking Decision", section: 12, component: "ChunkingDecision" },
  // Section 12 Act 4: Embed & Index Choices for RAG
  { id: "12.14", title: "Picking an Embedding Model", section: 12, component: "EmbeddingModelChoice" },
  { id: "12.15", title: "Domain Adaptation - Fine-Tuning Embeddings", section: 12, component: "DomainAdaptation" },
  { id: "12.16", title: "Hybrid Retrieval for RAG", section: 12, component: "HybridForRAG" },
  { id: "12.17", title: "The Reranker Cascade", section: 12, component: "RerankerCascade" },
  // Section 12 Act 5: Query Transformation
  { id: "12.18", title: "Why Transform Queries", section: 12, component: "WhyTransformQueries" },
  { id: "12.19", title: "HyDE - Hypothetical Document Embeddings", section: 12, component: "HyDE" },
  { id: "12.20", title: "Multi-Query Expansion", section: 12, component: "MultiQueryExpansion" },
  { id: "12.21", title: "Query Routing & Decomposition", section: 12, component: "QueryRoutingDecomposition" },
  // Section 12 Acts 6+7: Context & Generation, Advanced Retrieval Patterns
  { id: "12.22", title: "Context Packing", section: 12, component: "ContextPacking" },
  { id: "12.23", title: "The Lost-in-the-Middle Problem", section: 12, component: "LostInTheMiddle" },
  { id: "12.24", title: "Citations, Refusal & Groundedness", section: 12, component: "CitationsRefusal" },
  { id: "12.25", title: "Multi-Hop Retrieval", section: 12, component: "MultiHopRetrieval" },
  { id: "12.26", title: "Self-RAG", section: 12, component: "SelfRAG" },
  { id: "12.27", title: "CRAG - Corrective RAG", section: 12, component: "CorrectiveRAG" },
  { id: "12.28", title: "GraphRAG (Microsoft 2024)", section: 12, component: "GraphRAG" },
  { id: "12.29", title: "Tool-Augmented & Agentic RAG", section: 12, component: "AgenticRAG" },
  { id: "12.30", title: "Long-Context vs RAG", section: 12, component: "LongContextVsRAG" },
  // Section 12 Act 8: Evaluation
  { id: "12.31", title: "The RAG Eval Triangle", section: 12, component: "RAGEvalTriangle" },
  { id: "12.32", title: "LLM-as-Judge", section: 12, component: "LLMAsJudge" },
  { id: "12.33", title: "RAGAS Metrics", section: 12, component: "RAGASMetrics" },
  { id: "12.34", title: "Golden Datasets", section: 12, component: "GoldenDatasets" },
  { id: "12.35", title: "Online Eval & A/B Testing", section: 12, component: "OnlineEvalABTesting" },
];

export const sectionNames = {
  0: "Overview",
  1: "Neural Network Foundations",
  2: "How LLMs Actually Train",
  3: "Scaling & Modern Techniques",
  4: "The Road to Transformers",
  5: "Transformer Input Pipeline",
  6: "Attention - Understanding Q, K, V",
  7: "Attention - The Full Computation",
  8: "The Encoder",
  9: "The Decoder",
  10: "Modern LLM Techniques",
  11: "Vector Databases",
  12: "Retrieval-Augmented Generation",
};

// Section colors (one per section, used in progress bar, TOC, etc.)
export const sectionColors = {
  1: "#ff6b6b",
  2: "#00b8d4",
  3: "#ffd740",
  4: "#a78bfa",
  5: "#ffab40",
  6: "#00e676",
  7: "#e040fb",
  8: "#42a5f5",
  9: "#ef5350",
  10: "#26a69a",
  11: "#f06292",
  12: "#7c4dff",
};

// Colors
export const C = {
  bg: "#08080d",
  card: "rgba(255,255,255,0.025)",
  border: "rgba(255,255,255,0.07)",
  dim: "rgba(255,255,255,0.35)",
  mid: "rgba(255,255,255,0.55)",
  bright: "rgba(255,255,255,0.85)",
  red: "#ff6b6b",
  purple: "#a78bfa",
  green: "#00e676",
  cyan: "#00b8d4",
  yellow: "#ffd740",
  pink: "#e040fb",
  orange: "#ffab40",
  blue: "#42a5f5",
};

// Validate config - extracted for testability
export function validateConfig(chapterList) {
  const errors = [];
  const ids = chapterList.map((c) => c.id);
  const dupes = ids.filter((id, i) => ids.indexOf(id) !== i);
  if (dupes.length) errors.push(`Duplicate chapter IDs: ${dupes.join(", ")}`);
  chapterList.forEach((c) => {
    if (c.component && !c.id) errors.push(`Chapter missing id: ${c.component}`);
    if (!c.component) errors.push(`Chapter missing component: id=${c.id}`);
  });
  return errors;
}

// Config validation runs via tests (see config.test.js) using validateConfig().
