/**
 * Hybrid search engine: text (MiniSearch) + optional vector (cosine similarity).
 *
 * Text search works instantly with zero dependencies beyond MiniSearch (~6KB).
 * Semantic model is lazy-loaded (separate Vite chunk) - only fetched when
 * search is first opened, never on page load. Progress is tracked via
 * getSearchStatus() for the UI to show a loading indicator.
 *
 * Data files (generated by build scripts):
 *   src/data/chunks.json      - chunk text + metadata (used for text search)
 *   src/data/embeddings.json  - pre-computed 384d vectors only (parallel index to chunks)
 */
import MiniSearch from "minisearch";
import { getCachedEmbeddings, cacheEmbeddings } from "./embedding-cache.js";

// ── State ──
let miniSearch = null;
let chunks = [];
let vectors = [];
let embedPipeline = null;
let textReady = false;
let semanticReady = false;
let semanticLoading = false;
let loadProgress = 0; // 0-100 representing model download progress

// ── Status getter for UI ──
export function getSearchStatus() {
  if (semanticReady) return { mode: "semantic", progress: 100 };
  if (semanticLoading) return { mode: "loading", progress: loadProgress };
  if (textReady) return { mode: "text", progress: 0 };
  return { mode: "off", progress: 0 };
}

// ── Cosine similarity between two vectors ──
function cosineSim(a, b) {
  let dot = 0;
  let normA = 0;
  let normB = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i];
    normA += a[i] * a[i];
    normB += b[i] * b[i];
  }
  return dot / (Math.sqrt(normA) * Math.sqrt(normB) + 1e-8);
}

// ── Initialize text search (fast, no network) ──
export async function initSearch() {
  if (textReady) return;

  // Load chunk data for text search
  let chunkData;
  try {
    const mod = await import("./data/chunks.json");
    chunkData = mod.default || mod;
  } catch {
    console.warn("[search] chunks.json not found - search unavailable. Run: npm run search:extract");
    return;
  }

  chunks = Array.isArray(chunkData) ? chunkData : [];

  // Build MiniSearch index (instant - no network)
  miniSearch = new MiniSearch({
    fields: ["text", "title", "sectionName"],
    storeFields: ["chapterId", "title", "section", "sectionName", "sub", "text"],
    idField: "id",
    searchOptions: {
      boost: { title: 3, sectionName: 2, text: 1 },
      fuzzy: 0.2,
      prefix: true,
    },
  });
  miniSearch.addAll(chunks);

  textReady = true;

  // Start loading the semantic model in the background
  // This triggers a separate Vite chunk download - never blocks page load
  loadSemanticInBackground();
}

// ── Load semantic model + embeddings in background (never blocks UI) ──
function loadSemanticInBackground() {
  if (semanticReady || semanticLoading) return;
  semanticLoading = true;
  loadProgress = 0;

  // Track download steps for progress estimation when content-length is unavailable.
  // The model download has ~5 files. We track initiate/done pairs to estimate progress.
  let totalFiles = 0;
  let doneFiles = 0;

  // Load embeddings (with IndexedDB cache) + ML library in parallel
  Promise.all([
    // 1. Load pre-computed vectors: check IndexedDB cache first, download only on miss.
    //    In dev mode (npm run dev), always skip cache so you see fresh embeddings.
    import("./data/embeddings-checksum.json")
      .then(async (mod) => {
        const meta = mod.default || mod;
        const checksum = meta.checksum;
        // Skip cache in dev mode - always load fresh embeddings
        if (!import.meta.env.DEV) {
          const cached = await getCachedEmbeddings(checksum);
          if (cached) return cached;
        }
        // Download full embeddings (cache miss or dev mode)
        const embMod = await import("./data/embeddings.json");
        const vecs = (embMod.default || embMod).vectors || [];
        // Only cache in production
        if (!import.meta.env.DEV && vecs.length > 0) {
          cacheEmbeddings(checksum, vecs).catch(() => {});
        }
        return vecs;
      })
      .catch(() => []),
    // 2. Lazy-load transformers.js (Vite creates a separate chunk, only fetched here)
    import("@huggingface/transformers")
      .then(async (mod) => {
        loadProgress = 10; // Library loaded
        const { pipeline } = mod;
        // The HF CDN often omits Content-Length headers, causing the library to
        // log "Unable to determine content-length" warnings. Suppress that
        // specific message during model init - it's informational, not an error.
        const _warn = console.warn;
        console.warn = (...args) => {
          if (typeof args[0] === "string" && args[0].includes("Unable to determine content-length")) return;
          _warn.apply(console, args);
        };
        try {
          return await pipeline("feature-extraction", "Xenova/all-MiniLM-L6-v2", {
            dtype: "q8",
            progress_callback: (p) => {
              // If server sends content-length, we get real percentages
              if (p.status === "progress" && typeof p.progress === "number") {
                // Map model download progress (0-100) to our range (10-95)
                loadProgress = 10 + Math.round(p.progress * 0.85);
              }
              // If content-length is missing, estimate from file download events
              if (p.status === "initiate") {
                totalFiles++;
              }
              if (p.status === "done") {
                doneFiles++;
                // Estimate: library load = 10%, file downloads = 10-95%
                const filePct = totalFiles > 0 ? (doneFiles / totalFiles) : 0;
                const estimated = 10 + Math.round(filePct * 85);
                // Only update if we don't have real progress data
                if (loadProgress < estimated) loadProgress = estimated;
              }
              if (p.status === "ready") {
                loadProgress = 95;
              }
            },
          });
        } finally {
          console.warn = _warn;
        }
      }),
  ])
    .then(([loadedVectors, pipe]) => {
      // Allow vectors <= chunks: new chapters added since last embedding build
      // still get text search, just no vector coverage for the newest ones
      if (loadedVectors.length > 0 && loadedVectors.length <= chunks.length) {
        vectors = loadedVectors;
        embedPipeline = pipe;
        semanticReady = true;
        loadProgress = 100;
      }
      semanticLoading = false;
    })
    .catch(() => {
      semanticLoading = false;
      loadProgress = 0;
    });
}

// ── Embed a single query string ──
async function embedQuery(text) {
  if (!embedPipeline) return null;
  const result = await embedPipeline(text, { pooling: "mean", normalize: true });
  return result.tolist()[0];
}

// ── Vector search: find top K most similar chunks ──
// Note: vectors may cover fewer chunks than chunks.length if new chapters
// were added after embedding generation. We only search the covered range.
function vectorSearch(queryEmbedding, topK = 15) {
  const scored = vectors.map((vec, i) => ({
    index: i,
    score: cosineSim(queryEmbedding, vec),
  }));
  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, topK).map((s) => ({
    ...chunks[s.index],
    vectorScore: s.score,
  }));
}

// ── Text search with MiniSearch ──
function textSearch(query, topK = 15) {
  if (!miniSearch) return [];
  const results = miniSearch.search(query, { limit: topK });
  return results.map((r) => ({
    id: r.id,
    chapterId: r.chapterId,
    title: r.title,
    section: r.section,
    sectionName: r.sectionName,
    sub: r.sub,
    text: r.text,
    textScore: r.score,
  }));
}

// ── Reciprocal Rank Fusion: merge text + vector results ──
function reciprocalRankFusion(textResults, vectorResults, k = 60) {
  const scores = new Map();
  const dataMap = new Map();

  textResults.forEach((r, rank) => {
    const key = `${r.chapterId}:${r.sub}`;
    const rrf = 1 / (k + rank + 1);
    scores.set(key, (scores.get(key) || 0) + rrf);
    if (!dataMap.has(key)) dataMap.set(key, r);
  });

  vectorResults.forEach((r, rank) => {
    const key = `${r.chapterId}:${r.sub}`;
    const rrf = 1 / (k + rank + 1);
    scores.set(key, (scores.get(key) || 0) + rrf);
    if (!dataMap.has(key)) dataMap.set(key, r);
  });

  const fused = [...scores.entries()]
    .map(([key, score]) => ({ ...dataMap.get(key), fusedScore: score }))
    .sort((a, b) => b.fusedScore - a.fusedScore);

  const seen = new Set();
  const deduped = [];
  for (const r of fused) {
    if (!seen.has(r.chapterId)) {
      seen.add(r.chapterId);
      deduped.push(r);
    }
  }

  return deduped;
}

/**
 * Main search function - always instant, upgrades to hybrid when ready.
 */
export async function search(query, { limit = 10 } = {}) {
  if (!textReady) await initSearch();
  if (!miniSearch) return [];

  const trimmed = query.trim();
  if (!trimmed) return [];

  const textResults = textSearch(trimmed);

  if (!semanticReady || vectors.length === 0) {
    return textResults.slice(0, limit).map((r) => ({
      chapterId: r.chapterId,
      title: r.title,
      section: r.section,
      sectionName: r.sectionName,
      sub: r.sub,
      text: r.text,
      source: "text",
    }));
  }

  let vectorResults = [];
  try {
    const queryEmb = await embedQuery(trimmed);
    if (queryEmb) {
      vectorResults = vectorSearch(queryEmb);
    }
  } catch {
    // Fall back to text-only
  }

  if (vectorResults.length === 0) {
    return textResults.slice(0, limit).map((r) => ({
      chapterId: r.chapterId,
      title: r.title,
      section: r.section,
      sectionName: r.sectionName,
      sub: r.sub,
      text: r.text,
      source: "text",
    }));
  }

  const fused = reciprocalRankFusion(textResults, vectorResults);

  return fused.slice(0, limit).map((r) => ({
    chapterId: r.chapterId,
    title: r.title,
    section: r.section,
    sectionName: r.sectionName,
    sub: r.sub,
    text: r.text,
    source: "hybrid",
  }));
}

/**
 * Text-only search (no model loading, instant results).
 * Use this for real-time "search as you type".
 */
export function searchText(query, limit = 10) {
  if (!miniSearch) return [];
  const trimmed = query.trim();
  if (!trimmed) return [];

  const results = textSearch(trimmed);
  const seen = new Set();
  const deduped = [];
  for (const r of results) {
    if (!seen.has(r.chapterId)) {
      seen.add(r.chapterId);
      deduped.push(r);
    }
  }

  return deduped.slice(0, limit).map((r) => ({
    chapterId: r.chapterId,
    title: r.title,
    section: r.section,
    sectionName: r.sectionName,
    sub: r.sub,
    text: r.text,
    source: "text",
  }));
}
